.changeset/plenty-foxes-doubt.md, apps/sample/src/app/cal/page.tsx, apps/sample/src/components/CalView/CalAvailabilityResponse.tsx, apps/sample/src/components/CalView/CalNetworkDataSource.ts, apps/sample/src/components/CalView/index.tsx, apps/sample/src/components/Menu/index.tsx
Add in menu  `Crypto Assets` entry that will allow to check smart contracts descriptors availability inside the CAL service. 
- **JIRA or GitHub link**: [DSDK-451](https://ledgerhq.atlassian.net/browse/DSDK-451) 
- **Feature**:
---
[DSDK-451]: https://ledgerhq.atlassian.net/browse/DSDK-451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (sample) [DSDK-451]: Add CAL view for checking contracts availability

.github/workflows/release.yml
Use our own runner as shared-medium are not available anymore for public repos
Release DMK and DSK
---
=> 💚 (repo) [NOISSUE]: Change runner for release workflow

.github/workflows/pull_request.yml, .github/workflows/version.yml, danger/dangerfile-ci.ts, danger/helpers.ts
Various ajustments done to configuration and setup after we made a release and some issues came to light
- **JIRA or GitHub link**: NO-ISSUE
- **Feature**:
---
=> 🔧 (repo) [NO-ISSUE]: Small fixes that came to light with release

.github/dependabot.yml, .github/workflows/generate_sbom.yml, .github/workflows/snapshot_release.yml, .github/workflows/version.yml
Small updates / typos fixes so our CI actually follows our convention (some message where not passing danger)
Remove the specific config on dependabot for the `sample` app, as I never got it to work correctly 
Also since we are on a monorepo, when we target a sub directroy, the pnpm-lockfile does not get updated, leading to us usually finishing dependabot PRs manually
HOWEVER, because there is some catch, we will "always" (unless we find a way to bump TS with the current StyledComponents and LedgerHQ react UI libs in the sample app) have to take care of typescript updates manually (removing the bump from the sample app mostly and rerunning pmpm i)
- **Feature**:
Pull Requests must pass CI checks and undergo code review. Set the PR as Draft if it is …
=> 🩹 (repo) [NO-ISSUE]: Small maintenance update on repo

.changeset/mighty-vans-kiss.md, packages/signer/keyring-btc/src/internal/data-store/service/DataStoreService.ts, packages/signer/keyring-btc/src/internal/data-store/service/DefaultDataStoreService.test.ts, packages/signer/keyring-btc/src/internal/data-store/service/DefaultDataStoreService.ts, packages/signer/keyring-btc/src/internal/wallet/di/walletModule.test.ts, packages/signer/keyring-btc/src/internal/wallet/di/walletModule.ts, packages/signer/keyring-btc/src/internal/wallet/di/walletTypes.ts, packages/signer/keyring-btc/src/internal/wallet/model/Wallet.ts, packages/signer/keyring-btc/src/internal/wallet/service/DefaultWalletBuilder.test.ts, packages/signer/keyring-btc/src/internal/wallet/service/DefaultWalletBuilder.ts, packages/signer/keyring-btc/src/internal/wallet/service/DefaultWalletSerializer.test.ts, packages/signer/keyring-btc/src/internal/wallet/service/DefaultWalletSerializer.ts, packages/signer/keyring-btc/src/internal/wallet/service/WalletBuilder.ts, packages/signer/keyring-btc/src/internal/wallet/service/WalletSerializer.ts
This service should create a wallet policy serializable for the nano app, from Default or Registered wallets given through the API.
- **JIRA**: https://ledgerhq.atlassian.net/browse/DSDK-461
Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.
- ...
---
=> :sparkles: (keyring-btc) [DSDK-461]: Implement wallet policy service

.github/workflows/update_toolchain.yml
Adds a new workflow to update our current toolchain to the newest version
In proto language, newest = newest in your major, latest = the actual latest version published
Example 
| Package        | Curent         | Newest  |  Latest  |
| ------------- | ------------- | --- | --- |
|  node         | 20.17.0       | 20.18.0 | 22.9.0 |
Unless we pass `--latest` to `proto oudated --update` it will take the `newest` version.
- **Feature**:
- new update workflow for proto toolchain
---
=> 💚 (automation) [NO-ISSUE]: Automate the update of our toolchain

CODEOWNERS
To make things a bit easier to handle, I've added a CODEOWNERS file that we've forgotten when open sourcing the project
- **Feature**:
---
=> 📝 (repo) [NO-ISSUE]: Add CODEOWNERS file

.changeset/plenty-snakes-agree.md, packages/signer/keyring-eth/src/internal/app-binder/command/ProvideTransactionInformationCommand.test.ts, packages/signer/keyring-eth/src/internal/app-binder/command/ProvideTransactionInformationCommand.ts
Add `ProvideTransactionInformation` command.
The `ins` is not yet defined.
- **JIRA or GitHub link**: [DSDK-522]
- **Feature**:
---
[DSDK-522]: https://ledgerhq.atlassian.net/browse/DSDK-522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (keyring-eth) [DSDK-522]: Add ProvideTransactionInformation command

.changeset/slow-lies-float.md, packages/signer/keyring-eth/src/internal/app-binder/command/ProvideTransactionFieldDescriptionCommand.test.ts, packages/signer/keyring-eth/src/internal/app-binder/command/ProvideTransactionFieldDescriptionCommand.ts
Add ProvideTransactionFieldDescription command
- **JIRA or GitHub link**: [DSDK-524]
- **Feature**:
---
[DSDK-524]: https://ledgerhq.atlassian.net/browse/DSDK-524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (keyring-eth) [DSDK-524]: Add ProvideTransactionFieldDescription command

.changeset/eleven-spies-explain.md
=> :bug: (chore) [NO-ISSUE]: Fix broken changeset for snapshot release

.changeset/fuzzy-cups-refuse.md, packages/signer/keyring-eth/package.json, packages/signer/keyring-eth/src/internal/app-binder/command/SignTransactionCommand.test.ts, packages/signer/keyring-eth/src/internal/app-binder/command/StartTransactionCommand.ts, packages/signer/keyring-eth/src/internal/app-binder/command/StoreTransactionCommand.ts, packages/signer/keyring-eth/src/internal/app-binder/task/SendSignTransactionTask.test.ts, packages/signer/keyring-eth/src/internal/app-binder/task/SendSignTransactionTask.ts
Add support to SignTransaction for the incoming version of Ethereum app 1.13
The tests files have not changed, they have been update to comply with the current tests (legacy mode of SignTransaction). More tests to come in subsequent PRs.
- **JIRA or GitHub link**: [DSDK-521]
- **Feature**:
- Adapt SignTransactionCommand
- Add StoreTransactionCommand
- Update SendSignTransactionTask to use legacy mode by default
---
[DSDK-521]: https://ledgerhq.atlassian.net/browse/DSDK-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (keyring-eth) [DSDK-521]: Adapt SignTransactionCommand + new StoreTransactionCommand

packages/signer/keyring-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.test.ts, packages/signer/keyring-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.ts, packages/signer/keyring-eth/src/internal/app-binder/task/SendSignTransactionTask.test.ts, packages/signer/keyring-eth/src/internal/app-binder/task/SendSignTransactionTask.ts
- **✨ (keyring-eth): Update SendSignTransactionTask**
Update SendSignTransactionTask for the incoming Ethereum app 1.13
Needs #417 
- **JIRA or GitHub link**: [DSDK-526]
- **Feature**:
- Updated SendSignTransactionTask
- Updated SignTransactionDeviceAction to match the new args
---
[DSDK-526]: https://ledgerhq.atlassian.net/browse/DSDK-526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (keyring-eth) [DSDK-526]: Update SendSignTransactionTask

packages/core/package.json, packages/signer/context-module/package.json, packages/signer/keyring-btc/package.json, packages/signer/keyring-eth/package.json, packages/tools/esbuild-tools/build.mjs, packages/tools/esbuild-tools/watch.mjs, packages/transport-mock/package.json, packages/trusted-apps/package.json, packages/ui/package.json
@aussedatlo pointed out to me some new warnings when creating a build for the sample app.
It seems it was due to the bundling of the libraries as a single file, the nextjs bundler was having issue creating optimized builds.
I have updated the build config to make sure we do not bundle our packages anymore.
The drawback was that, no bundling, makes esbuild skip the tsconfig path alias resolution and just keeps the alias (same as type definitions created by tsc) thus we need to transform those after the builds
- **JIRA or GitHub link**: slack discussion with @aussedatlo
- **Feature**:
- going back to unbundled libraries
---
=> 🔨 (repo) [NO-ISSUE]: Update esbuild config to not use bundling

packages/tools/esbuild-tools/build.mjs, packages/tools/esbuild-tools/watch.mjs
Updates to make the esbuild watch mode recompile the alias on watch
- **Feature**:
---
=> 🔨 (esbuild) [NO-ISSUE]: Update to make it work with watch mode

.changeset/tiny-hornets-grin.md, apps/sample/src/components/CommandsView/CommandForm.tsx, apps/sample/src/components/DeviceActionsView/AllDeviceActions.tsx, packages/core/src/api/device-action/__test-utils__/setupTestMachine.ts, packages/core/src/api/device-action/os/GetDeviceStatus/GetDeviceStatusDeviceAction.ts, packages/core/src/api/device-action/os/GetDeviceStatus/types.ts, packages/core/src/api/device-action/os/GoToDashboard/GoToDashboardDeviceAction.test.ts, packages/core/src/api/device-action/os/OpenAppDeviceAction/OpenAppDeviceAction.test.ts, packages/core/src/api/device-action/os/OpenAppDeviceAction/OpenAppDeviceAction.ts, packages/core/src/api/device-action/os/OpenAppDeviceAction/types.ts
- Use unlockTimeout param in execute device actions
- Add unlockTimeout in OpenAppDA
- OpenAppDA calls GetDeviceStatusDA instead of GetAppAndVersionCmd
- **JIRA or GitHub link**: [DSDK-456]
- **Feature**:
---
[DSDK-456]: https://ledgerhq.atlassian.net/browse/DSDK-456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 🐛 (core) [DSDK-456]: User does not received User action required: unlock-device during an Open app Device action

packages/tools/esbuild-tools/watch.mjs
Ensure the folder is created before initiating the copy
Make sure we create the lib/[esm|cjs] folders before copying package.json into it
- **Feature**:
---
=> 🔨 (esbuild) [NO-ISSUE]: Copy package.json after the first build

.changeset/afraid-readers-swim.md, packages/signer/context-module/src/shared/model/ClearSignContext.ts, packages/signer/keyring-eth/src/internal/app-binder/command/ProvideEnumCommand.ts, packages/signer/keyring-eth/src/internal/app-binder/command/ProvideTransactionFieldDescriptionCommand.ts, packages/signer/keyring-eth/src/internal/app-binder/command/ProvideTransactionInformationCommand.ts, packages/signer/keyring-eth/src/internal/app-binder/task/ProvideTransactionContextTask.test.ts, packages/signer/keyring-eth/src/internal/app-binder/task/ProvideTransactionContextTask.ts, packages/signer/keyring-eth/src/internal/app-binder/task/ProvideTransactionGenericContextTask.ts, packages/signer/keyring-eth/src/internal/app-binder/task/SendCommandInChunksTask.ts, packages/signer/keyring-eth/src/internal/app-binder/task/SendSignPersonalMessageTask.ts, packages/signer/keyring-eth/src/internal/app-binder/task/SendSignTransactionTask.ts, packages/signer/keyring-eth/src/internal/shared/utils/DerivationPathUtils.test.ts, packages/signer/keyring-eth/src/internal/shared/utils/DerivationPathUtils.ts, packages/signer/keyring-eth/src/internal/shared/utils/PayloadUtils.ts
Add `ProvideTransactionGenericContextTask`
- **JIRA or GitHub link**: [DSDK-525]
- **Feature**:
---
[DSDK-525]: https://ledgerhq.atlassian.net/browse/DSDK-525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 🚧 (keyring-eth) [DSDK-525]: Add ProvideTransactionGenericContext Task

.changeset/cool-dancers-join.md, README.md, package.json, packages/config/eslint/package.json, packages/config/jest/package.json, packages/config/prettier/package.json, packages/config/typescript/package.json, packages/core/package.json, packages/flipper-plugin-client/package.json, packages/signer/context-module/package.json, packages/signer/keyring-btc/package.json, packages/signer/keyring-eth/package.json, packages/tools/esbuild-tools/package.json, packages/transport-mock/package.json, packages/trusted-apps/package.json, packages/ui/package.json
We've updated the LICENSE.md file but did not replace the license in the package.json
This PR fixes that
- **Feature**:
---
=> 📄 (repo) [NO-ISSUE]: Update package.json `license` key

apps/sample/src/components/ClickableListItem.tsx, apps/sample/src/components/MockView/MockDeviceDrawer.tsx, apps/sample/src/components/MockView/MockItem.tsx, apps/sample/src/components/MockView/index.tsx, apps/sample/src/components/StyledDrawer.tsx, apps/sample/src/styles/globalstyles.tsx
List & drawer for mock sessions
https://github.com/user-attachments/assets/b3de4418-2050-4b0b-ba2c-34fd6fd5b24b
- **Feature**:
---
=> :lipstick: (smpl) [NO-ISSUE]: Improve mock settings page

.changeset/tiny-otters-draw.md, apps/sample/src/app/client-layout.tsx, apps/sample/src/components/CalView/CalCheckDappDrawer.tsx, apps/sample/src/components/CalView/CalNetworkDataSource.ts, apps/sample/src/components/CalView/CalSettingsDrawer.tsx, apps/sample/src/components/CalView/index.tsx, apps/sample/src/components/CommandsView/CommandForm.tsx, apps/sample/src/components/KeyringEthView/index.tsx, apps/sample/src/components/KeyringView/index.tsx, apps/sample/src/providers/KeyringEthProvider/index.tsx
Add a provider for the keyring eth. Allow the modification of the CAL config, and reload the keyring if the configuration change.
[DSDK-539]
- **Feature**:
---
[DSDK-539]: https://ledgerhq.atlassian.net/browse/DSDK-539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (sample) [DSDK-539]: Add keyring eth provider

.changeset/nasty-horses-wash.md
Replace `device-sdk-core` by `device-management-kit`.
- **Feature**:
---
=> 🔖 (repo) [NO-ISSUE]: Fix outdated changeset

.changeset/swift-doors-retire.md, packages/signer/signer-solana/src/api/SignerSolana.ts, packages/signer/signer-solana/src/api/app-binder/GetAddressDeviceActionTypes.ts, packages/signer/signer-solana/src/api/app-binder/GetAppConfigurationDeviceActionTypes.ts, packages/signer/signer-solana/src/api/app-binder/SignMessageDeviceActionTypes.ts, packages/signer/signer-solana/src/api/app-binder/SignTransactionDeviceActionTypes.ts, packages/signer/signer-solana/src/api/model/AddressOption.ts, packages/signer/signer-solana/src/api/model/AppConfiguration.ts, packages/signer/signer-solana/src/api/model/PublicKey.ts, packages/signer/signer-solana/src/api/model/PublicKeyDisplayMode.ts, packages/signer/signer-solana/src/api/model/Signature.ts, packages/signer/signer-solana/src/api/model/Transaction.ts, packages/signer/signer-solana/src/api/model/TransactionOptions.ts
Add `SignerSolana` interface with 4 functions:
- `signTransaction`
- `signMessage` 
- `getAddress`
- `getAppConfiguration`
- **JIRA or GitHub link**: [DSDK-549]
- **Feature**:
---
[DSDK-549]: https://ledgerhq.atlassian.net/browse/DSDK-549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (signer-solana) [DSDK-549]: Add SignerSolana interface and models

.changeset/blue-berries-jump.md, packages/signer/signer-solana/package.json, packages/signer/signer-solana/src/api/model/PublicKey.ts, packages/signer/signer-solana/src/internal/app-binder/command/GetPubKeyCommand.test.ts, packages/signer/signer-solana/src/internal/app-binder/command/GetPubKeyCommand.ts, pnpm-lock.yaml
Create `GetPubKeyCommand` for the `signer-solana`.
The return type is a bit different from `ethereum` since we return the address in a `bs58` format.
- **JIRA or GitHub link**: [DSDK-550]
- **Feature**:
---
[DSDK-550]: https://ledgerhq.atlassian.net/browse/DSDK-550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (signer-solana) [DSDK-550]: Add GetPubKey command

.changeset/neat-olives-train.md, packages/signer/signer-solana/src/api/SignerSolanaBuilder.ts, packages/signer/signer-solana/src/internal/DefaultSignerSolana.test.ts, packages/signer/signer-solana/src/internal/DefaultSignerSolana.ts, packages/signer/signer-solana/src/internal/app-binder/SolanaAppBinder.test.ts, packages/signer/signer-solana/src/internal/app-binder/SolanaAppBinder.ts, packages/signer/signer-solana/src/internal/app-binder/di/appBinderModule.test.ts, packages/signer/signer-solana/src/internal/app-binder/di/appBinderModule.ts, packages/signer/signer-solana/src/internal/app-binder/di/appBinderTypes.ts, packages/signer/signer-solana/src/internal/di.ts, packages/signer/signer-solana/src/internal/externalTypes.ts
Add DefaultSignerSolana and SolanaAppBinder to prepare for use cases development.
- **Feature**: [DSDK-561]
---
[DSDK-561]: https://ledgerhq.atlassian.net/browse/DSDK-561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (signer-solana) [DSDK-561]: Add DefaultSignerSolana and SolanaAppBinder

README.md
=> ✏️ (readme) [NO-ISSUE]: Fixed readme typo

.changeset/tall-books-juggle.md, packages/signer/signer-solana/src/internal/app-binder/command/SignOffChainMessageCommand.test.ts, packages/signer/signer-solana/src/internal/app-binder/command/SignOffChainMessageCommand.ts
Added SignOffChainMessage
- **JIRA or GitHub link**: [DSDK-553](https://ledgerhq.atlassian.net/browse/DSDK-553)
---
[DSDK-553]: https://ledgerhq.atlassian.net/browse/DSDK-553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (signer-solana) [DSDK-553]: Create sign off chain message command

.changeset/grumpy-geese-sip.md, packages/signer/signer-solana/src/api/model/Signature.ts, packages/signer/signer-solana/src/internal/app-binder/command/SignTransactionCommand.test.ts, packages/signer/signer-solana/src/internal/app-binder/command/SignTransactionCommand.ts
Add `SignTransactionCommand`.
- **JIRA or GitHub link**: [DSDK-551]
- **Feature**:
---
[DSDK-551]: https://ledgerhq.atlassian.net/browse/DSDK-551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (signer-solana) [DSDK-551]: Add SignTransactionCommand

.changeset/happy-shirts-double.md, apps/sample/src/providers/DeviceSessionsProvider/index.tsx, packages/device-management-kit/src/api/DeviceManagementKit.test.ts, packages/device-management-kit/src/api/DeviceManagementKit.ts, packages/device-management-kit/src/api/transport/model/ConnectedDevice.ts, packages/device-management-kit/src/internal/device-session/di/deviceSessionModule.ts, packages/device-management-kit/src/internal/device-session/di/deviceSessionTypes.ts, packages/device-management-kit/src/internal/device-session/model/DeviceSession.ts, packages/device-management-kit/src/internal/device-session/service/DefaultDeviceSessionService.test.ts, packages/device-management-kit/src/internal/device-session/service/DefaultDeviceSessionService.ts, packages/device-management-kit/src/internal/device-session/service/DeviceSessionService.ts, packages/device-management-kit/src/internal/discovery/di/discoveryModule.test.ts, packages/device-management-kit/src/internal/discovery/di/discoveryModule.ts, packages/device-management-kit/src/internal/discovery/di/discoveryTypes.ts, packages/device-management-kit/src/internal/discovery/use-case/ListConnectedDevicesUseCase.test.ts, packages/device-management-kit/src/internal/discovery/use-case/ListConnectedDevicesUseCase.ts, packages/device-management-kit/src/internal/discovery/use-case/ListenToConnectedDeviceUseCase.test.ts, packages/device-management-kit/src/internal/discovery/use-case/ListenToConnectedDeviceUseCase.ts
- Remove `ListDeviceSessionsUseCase`
- Create `ListConnectedDevicesUseCase` and `ListenToConnectedDeviceUseCase`
- Update Sample app
- Update `ConnectedDevice` model to add `sessionId`
- **JIRA or GitHub link**: [DSDK-571]
- **Feature**:
---
[DSDK-571]: https://ledgerhq.atlassian.net/browse/DSDK-571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> :recycle: (dmk) [DSDK-571]: Refactor ListDeviceSession into ListConnectedDevice

.github/workflows/pull_request.yml, packages/device-management-kit/index.ts
Just a test
- **Feature**:
---
=> 🚧 (repo) [NO-ISSUE]: Testing merge queues

.github/workflows/merge_queue.yml
Setup a new workflow that triggers on merge_queue
When this PR is merged to develop, we will enable a new "develop" branch ruleset to enable merge queues (we will only enable it as "evaluate" for a week, then proceed to do the final switch if evrything is working fine)
- **JIRA or GitHub link**: [DSDk-555]
- **Feature**:
- new merge queue workflow
---
=> 👷 (repo) [DSDK-555]: Setup merge queues

.github/workflows/merge_queue.yml
Remove unused arguments from the commands in merge_queue workflow
- **Feature**:
---
=> 💚 (merge-queues) [NO-ISSUE]: Remove unused arguments

.github/workflows/merge_queue.yml, .github/workflows/pull_request.yml, .github/workflows/update_toolchain.yml, package.json, packages/device-management-kit/jest.config.ts, packages/device-management-kit/src/internal/device-session/service/DefaultDeviceSessionService.test.ts, packages/device-management-kit/src/internal/discovery/use-case/ConnectUseCase.test.ts, packages/flipper-plugin-client/jest.config.ts, packages/signer/context-module/jest.config.ts, packages/signer/signer-btc/jest.config.ts, packages/signer/signer-eth/jest.config.ts, packages/signer/signer-solana/jest.config.ts, packages/signer/signer-utils/jest.config.ts, packages/transport-mock/jest.config.ts, turbo.json
Sonarqube has been broken since me moved the repo to public. This PR aims to fix it.
- **Feature**:
---
=> 💚 (sonarqube) [NO-ISSUE]: Reenable sonarqube

.changeset/slow-bats-ring.md, apps/docs/pages/docs/explanations/signers.mdx, apps/docs/pages/docs/explanations/signers/solana.mdx, packages/signer/signer-solana/README.md, packages/signer/signer-solana/src/api/SignerSolanaBuilder.ts
Update Solana signer documentation
- **JIRA or GitHub link**: [DSDK-584]
- **Feature**:
---
[DSDK-584]: https://ledgerhq.atlassian.net/browse/DSDK-584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 📝 (signer-solana) [DSDK-584]: Update documentation

.changeset/config.json
Update on the ignored packages for the release
- **Feature**:
---
=> 🔧 (changesets) [NO-ISSUE]: Ignored packages

.changeset/calm-months-live.md, .changeset/cuddly-impalas-sing.md, .changeset/lucky-keys-explode.md, .changeset/mighty-vans-kiss.md, .changeset/perfect-deers-sneeze.md, .changeset/tall-hairs-cheer.md, .changeset/weak-ads-chew.md, package.json, packages/signer/signer-btc/package.json
Replace `@ledgerhq/device-signer-kit-btc` with `@ledgerhq/device-signer-kit-bitcoin`.
- **JIRA or GitHub link**: [DSDK-590]
- **Feature**:
---
[DSDK-590]: https://ledgerhq.atlassian.net/browse/DSDK-590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 🔧 (signer-btc) [DSDK-590]: Rename package name to device-signer-kit-bitcoin

.github/workflows/pull_request.yml
Condition was checking for a "true" value as string when in fact it's a boolean
- **Feature**:
---
=> 💚 (ci) [NO-ISSUE]: Fix condition in pull_request.yml

.changeset/calm-monkeys-peel.md, packages/signer/signer-btc/src/internal/app-binder/command/RegisterWalletAddressCommand.test.ts, packages/signer/signer-btc/src/internal/app-binder/command/RegisterWalletAddressCommand.ts, packages/signer/signer-btc/src/internal/app-binder/command/utils/constants.ts
Implement RegisterWallet Command
- **JIRA or GitHub link**: [DSDK-466]
- **Feature**:
---
[DSDK-466]: https://ledgerhq.atlassian.net/browse/DSDK-466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> :sparkles: (signer-btc) [DSDK-466]: Implement RegisterWallet Command

.changeset/quiet-feet-leave.md, packages/signer/signer-btc/src/internal/app-binder/command/GetWalletAddressCommand.test.ts, packages/signer/signer-btc/src/internal/app-binder/command/GetWalletAddressCommand.ts, packages/signer/signer-btc/src/internal/app-binder/command/utils/bitcoinAppError.test.ts, packages/signer/signer-btc/src/internal/app-binder/command/utils/bitcoinAppErrors.ts
Added GetWalletAddressCommand
- **JIRA or GitHub link**: [DSDK-465](https://ledgerhq.atlassian.net/browse/DSDK-465)
---
[DSDK-465]: https://ledgerhq.atlassian.net/browse/DSDK-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (btc-signer) [DSDK-465]: Add GetWalletAddressCommand

.changeset/large-olives-think.md, packages/device-management-kit/src/api/apdu/utils/ByteArrayBuilder.test.ts, packages/device-management-kit/src/api/apdu/utils/ByteArrayBuilder.ts, packages/device-management-kit/src/api/apdu/utils/ByteArrayParser.test.ts, packages/device-management-kit/src/api/apdu/utils/ByteArrayParser.ts, packages/signer/context-module/src/index.ts, packages/signer/context-module/src/shared/model/GenericPath.ts, packages/signer/signer-eth/src/internal/transaction/service/parser/TransactionParserService.test.ts, packages/signer/signer-eth/src/internal/transaction/service/parser/TransactionParserService.ts
CAL descriptors for the generic parser contains references to variables in the transaction calldata.
To locate those data, they are referenced using a binary path to navigate un the calldata buffer.
Binary path documentation is available here:
https://ledgerhq.atlassian.net/wiki/spaces/TA/pages/3274113097/Arch+-+CAL+B2C+Binary+Path+Format
"real life" examples can be fetched from the cal, such as here:
https://crypto-assets-service.api.ledger.com/v1/dapps?ref=branch:next&chain_id=1&contracts=0x1111111254EEB25477B68fb85Ed929f73A960582&output=descriptors_calldata
even if it can not be entirely tested until we have an ethereum application with the generic parser
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/DSDK-583
- **Feature**: Generic parser
Pull Requests must pass CI …
=> :sparkles: (signer-eth) [DSDK-583]: Implement parser of binary paths for transactions

.changeset/gold-dots-accept.md, apps/sample/src/providers/SignerEthProvider/index.tsx, packages/signer/context-module/README.md, packages/signer/context-module/src/ContextModuleBuilder.test.ts, packages/signer/context-module/src/ContextModuleBuilder.ts, packages/signer/context-module/src/DefaultContextModule.test.ts, packages/signer/context-module/src/DefaultContextModule.ts, packages/signer/context-module/src/config/model/ContextModuleConfig.ts
Rework context module builder:
- use inversify in default implem instead of builder
- change builder entry function to match other builder naming (replace `with` by `add`)
- **Feature**:
---
=> ♻️ (context-module) [NO-ISSUE]: Rework context module builder

.changeset/eighty-houses-heal.md, packages/signer/context-module/src/DefaultContextModule.ts, packages/signer/context-module/src/di.ts, packages/signer/context-module/src/shared/model/ClearSignContext.ts, packages/signer/context-module/src/transaction/data/CalldataDto.ts, packages/signer/context-module/src/transaction/data/HttpTransactionDataSource.test.ts, packages/signer/context-module/src/transaction/data/HttpTransactionDataSource.ts, packages/signer/context-module/src/transaction/data/TransactionDataSource.ts, packages/signer/context-module/src/transaction/di/transactionModuleFactory.ts, packages/signer/context-module/src/transaction/di/transactionTypes.ts, packages/signer/context-module/src/transaction/domain/TransactionContextLoader.test.ts, packages/signer/context-module/src/transaction/domain/TransactionContextLoader.ts, packages/signer/signer-eth/src/api/SignerEthBuilder.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/ProvideTransactionContextTask.ts, packages/signer/signer-eth/src/internal/app-binder/task/ProvideTransactionGenericContextTask.ts
Implement the context loader for generic parser transactions.
Documentation is here:
https://ledgerhq.atlassian.net/wiki/spaces/BE/pages/5072093201/CAL+service+-+Generic+Parser+descriptors+API+specifications?atlOrigin=eyJpIjoiYWY1NTJlNzE0OTMwNDJhNzlmN2Q1NjJhNzhiMmFmMDgiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ
Some examples are available here:
https://crypto-assets-service.api.ledger.com/v1/dapps?ref=branch:next&chain_id=1&contracts=0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9&output=descriptors_calldata
https://crypto-assets-service.api.ledger.com/v1/dapps?ref=branch:next&chain_id=1&contracts=0x1111111254EEB25477B68fb85Ed929f73A960582&output=descriptors_calldata
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/DSDK-528
- **Feature**:
Pull Requests must pass CI checks and …
=> :sparkles: (context-module) [DSDK-528]: Implement generic transaction context loader

.github/workflows/generate_sbom.yml, .github/workflows/merge_queue.yml, .github/workflows/pull_request.yml, .github/workflows/version.yml
Fix version for runners to avoid funky suprises
Also switched the merge queue workflow to github runners as we do not require "speed" on the merge group _for now_
- **Feature**:
- workflows
---
=> 👷 (ci) [NO-ISSUE]: Fix ubuntu version + merge queue on gh runners

.changeset/good-mayflies-jog.md, packages/signer/signer-btc/src/internal/app-binder/command/SignMessageCommand.test.ts, packages/signer/signer-btc/src/internal/app-binder/command/SignMessageCommand.ts, packages/signer/signer-btc/src/internal/app-binder/command/utils/bitcoinAppErrors.ts
Implemented GetSignMessageCommand and added BtcDerivationPathUtils
- **JIRA or GitHub link**: [DSDK-467](https://ledgerhq.atlassian.net/browse/DSDK-467)
---
[DSDK-467]: https://ledgerhq.atlassian.net/browse/DSDK-467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (signer-btc) [DSDK-467]: Implement getSignMessageCommand

packages/signer/signer-eth/src/internal/app-binder/command/ProvideEnumCommand.ts, packages/signer/signer-eth/src/internal/app-binder/command/ProvideTransactionFieldDescriptionCommand.ts, packages/signer/signer-eth/src/internal/app-binder/command/ProvideTransactionInformationCommand.ts, packages/signer/signer-eth/src/internal/app-binder/task/ProvideTransactionGenericContextTask.ts
We now have more detailed informations on generic parser behaviour, and CAL descriptors.
More informations in the jira ticket, and here: https://github.com/LedgerHQ/generic_parser/blob/master/specs.md
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/DSDK-594
- **Feature**:
---
=> :sparkles: (context-module) [DSDK-594]: Update ProvideGenericContext task

.changeset/little-camels-approve.md, packages/signer/context-module/src/transaction/data/CalldataDto.ts, packages/signer/context-module/src/transaction/data/HttpTransactionDataSource.test.ts, packages/signer/context-module/src/transaction/data/HttpTransactionDataSource.ts, packages/signer/context-module/src/trusted-name/data/HttpTrustedNameDataSource.test.ts, packages/signer/context-module/src/trusted-name/data/HttpTrustedNameDataSource.ts, packages/signer/signer-eth/src/api/app-binder/SignTransactionDeviceActionTypes.ts, packages/signer/signer-eth/src/internal/app-binder/EthAppBinder.test.ts, packages/signer/signer-eth/src/internal/app-binder/EthAppBinder.ts, packages/signer/signer-eth/src/internal/app-binder/command/StoreTransactionCommand.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.test.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildTransactionContextTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildTransactionContextTask.ts, packages/signer/signer-eth/src/internal/app-binder/task/ProvideTransactionGenericContextTask.ts, packages/signer/signer-eth/src/internal/app-binder/task/SendSignTransactionTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/SendSignTransactionTask.ts, packages/signer/signer-eth/src/internal/transaction/di/transactionModule.ts, packages/signer/signer-eth/src/internal/transaction/di/transactionTypes.ts, packages/signer/signer-eth/src/internal/transaction/service/parser/TransactionParserService.ts
The goal is to update the SignTransaction device action for generic parser support:
* if BuildContext task returns a generic-parser context, go to ProvideGenericContext state
* else go to ProvideContext state
* forward correct isLegacy parameter to SignTransaction task
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/DSDK-527
- **Feature**:
---
=> :sparkles: (context-module) [DSDK-527]: Update SignTransaction with generic-parser

.changeset/stale-buttons-repair.md, packages/signer/signer-solana/src/internal/app-binder/command/SignTransactionCommand.ts
Remove logs
- **Feature**:
---
=> 🔇 (signer-solana) [NO-ISSUE]: Remove debug logs

.changeset/twenty-beans-teach.md, packages/signer/signer-btc/package.json, packages/signer/signer-btc/src/api/SignerBtc.ts, packages/signer/signer-btc/src/api/app-binder/GetExtendedPublicKeyDeviceActionTypes.ts, packages/signer/signer-btc/src/api/index.ts, packages/signer/signer-btc/src/index.ts, packages/signer/signer-btc/src/internal/DefaultSignerBtc.test.ts, packages/signer/signer-btc/src/internal/DefaultSignerBtc.ts, packages/signer/signer-btc/src/internal/app-binder/BtcAppBinder.test.ts, packages/signer/signer-btc/src/internal/app-binder/BtcAppBinder.ts, packages/signer/signer-btc/src/internal/app-binder/command/GetExtendedPublicKeyCommand.test.ts, packages/signer/signer-btc/src/internal/app-binder/command/GetExtendedPublicKeyCommand.ts, packages/signer/signer-btc/src/internal/app-binder/di/appBinderModule.test.ts, packages/signer/signer-btc/src/internal/app-binder/di/appBinderModule.ts, packages/signer/signer-btc/src/internal/app-binder/di/appBinderTypes.ts, packages/signer/signer-btc/src/internal/di.ts, packages/signer/signer-btc/src/internal/externalTypes.ts, packages/signer/signer-btc/src/internal/use-cases/di/useCasesModule.test.ts, packages/signer/signer-btc/src/internal/use-cases/di/useCasesModule.ts, packages/signer/signer-btc/src/internal/use-cases/di/useCasesTypes.ts, packages/signer/signer-btc/src/internal/use-cases/get-extended-public-key/GetExtendedPublicKeyUseCase.test.ts, packages/signer/signer-btc/src/internal/use-cases/get-extended-public-key/GetExtendedPublicKeyUseCase.ts, pnpm-lock.yaml
Implement SignerBtc, DI & GetExtendedPkeyDA
- **JIRA or GitHub link**: [DSDK-475]
- **Feature**:
---
[DSDK-475]: https://ledgerhq.atlassian.net/browse/DSDK-475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> :sparkles: (signer-btc) [DSDK-475]: Implement GetExtendedPublicKey device action with DefaultSigner DI

.github/workflows/pull_request.yml
=> chore: replace secret by env variable

.changeset/breezy-bikes-train.md, .changeset/chilly-kangaroos-applaud.md, packages/signer/context-module/src/shared/model/ClearSignContext.ts, packages/signer/context-module/src/transaction/data/CalldataDto.ts, packages/signer/context-module/src/transaction/data/HttpTransactionDataSource.test.ts, packages/signer/context-module/src/transaction/data/HttpTransactionDataSource.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildTransactionContextTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildTransactionContextTask.ts, packages/signer/signer-eth/src/internal/app-binder/task/ProvideTransactionFieldDescriptionTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/ProvideTransactionFieldDescriptionTask.ts, packages/signer/signer-eth/src/internal/app-binder/task/ProvideTransactionGenericContextTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/ProvideTransactionGenericContextTask.ts
Add generic parser enums support.
- Context Module:
- `HttpTransactionDataSource`: Return `ENUM` with `value`, `id` (used to map the enum used in the transaction) and correct payload (as each enum contain its own signature). transform `ENUM` field in `TRANSACTION_FIELD_DESCRIPTION` with an `ENUM`reference.
- Signer Eth:
- `BuildTansactionGenericContextTask`: Filter `ENUM` context from all other `ClearSignContextSuccess` to use them differently in the next task
- `ProvideTransactionFieldDescriptionTask`: Provide `ENUM` reference context if needed.
- **JIRA or GitHub link**: [DSDK-601]
- **Feature**:
---
=> ✨ (signer-eth) [DSDK-601]: Add generic parser enums support

.changeset/breezy-crabs-boil.md, apps/sample/package.json, apps/sample/src/app/signer/bitcoin/page.tsx, apps/sample/src/components/SignerBtcView/index.tsx, packages/signer/signer-btc/src/api/SignerBtcBuiilder.test.ts, packages/signer/signer-btc/src/api/SignerBtcBuilder.ts, packages/signer/signer-btc/src/api/index.ts
Add KeyringBtc GetExtendedPublicKey in sample app
- **JIRA or GitHub link**: [DSDK-480]
- **Feature**:
---
[DSDK-480]: https://ledgerhq.atlassian.net/browse/DSDK-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 💄 (btc) [DSDK-480]: Add KeyringBtc GetExtendedPublicKey 

.changeset/shy-ads-suffer.md, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.test.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.ts
Fallback to blind sign if provide in error to avoid getting stuck when the clear signing is not working correctly or a plugin is not installed.
- **JIRA or GitHub link**: [DSDK-616]
- **Feature**:
---
[DSDK-616]: https://ledgerhq.atlassian.net/browse/DSDK-616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 🩹 (signer-eth) [DSDK-616]: Fallback to blind sign if provide in error

.changeset/eighty-ravens-love.md, .changeset/hungry-kangaroos-compete.md, packages/signer/context-module/src/shared/model/ClearSignContext.ts, packages/signer/context-module/src/transaction/data/CalldataDto.ts, packages/signer/context-module/src/transaction/data/HttpTransactionDataSource.test.ts, packages/signer/context-module/src/transaction/data/HttpTransactionDataSource.ts, packages/signer/signer-eth/src/internal/app-binder/task/ProvideTransactionFieldDescriptionTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/ProvideTransactionFieldDescriptionTask.ts
Add eip7730 constant support. (with token and nft only for now)
When a reference type is `constant` and not `path`, we do not need to parse the trasaction to extract the value, as the value is already provided. So we just call the context-module to fetch the satellite data and sent it to the device.
- **JIRA or GitHub link**: [DSDK-619]
- **Feature**:
---
[DSDK-619]: https://ledgerhq.atlassian.net/browse/DSDK-619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (signer-eth) [DSDK-619]: Add generic parser constant support

.github/workflows/snapshot_release.yml
Temporary solution (given to me by Thomas) to publish npm packages until jfrog implementation is finished
- **Feature**:
---
=> 💚 (release) [NO-ISSUE]: Temp snapshot release until jfrog fix

.changeset/purple-ears-drop.md, packages/device-management-kit/package.json, packages/device-management-kit/src/api/DeviceManagementKit.test.ts, packages/device-management-kit/src/api/DeviceManagementKitBuilder.ts, packages/device-management-kit/src/api/DmkConfig.ts, packages/device-management-kit/src/api/command/use-case/SendCommandUseCase.test.ts, packages/device-management-kit/src/api/device-session/use-case/ToggleDeviceSessionRefresher.test.ts, packages/device-management-kit/src/di.ts, packages/device-management-kit/src/internal/device-session/service/DefaultDeviceSessionService.test.ts, packages/device-management-kit/src/internal/device-session/use-case/CloseSessionsUseCase.test.ts, packages/device-management-kit/src/internal/device-session/use-case/GetDeviceSessionStateUseCase.test.ts, packages/device-management-kit/src/internal/discovery/di/discoveryModule.test.ts, packages/device-management-kit/src/internal/discovery/use-case/ConnectUseCase.test.ts, packages/device-management-kit/src/internal/discovery/use-case/DisconnectUseCase.test.ts, packages/device-management-kit/src/internal/discovery/use-case/GetConnectedDeviceUseCase.test.ts, packages/device-management-kit/src/internal/discovery/use-case/ListConnectedDevicesUseCase.test.ts, packages/device-management-kit/src/internal/discovery/use-case/ListenToConnectedDeviceUseCase.test.ts, packages/device-management-kit/src/internal/manager-api/data/AxiosManagerApiDataSource.test.ts, packages/device-management-kit/src/internal/manager-api/data/AxiosManagerApiDataSource.ts, packages/device-management-kit/src/internal/manager-api/data/ManagerApiDataSource.ts, packages/device-management-kit/src/internal/manager-api/data/__mocks__/AxiosManagerApiDataSource.ts, packages/device-management-kit/src/internal/manager-api/di/managerApiModule.test.ts, packages/device-management-kit/src/internal/manager-api/model/Const.ts, packages/device-management-kit/src/internal/manager-api/model/Errors.ts, packages/device-management-kit/src/internal/manager-api/model/Params.ts, packages/device-management-kit/src/internal/manager-api/service/DefaultManagerApiService.test.ts, packages/device-management-kit/src/internal/send/use-case/SendApduUseCase.test.ts, packages/device-management-kit/src/internal/transport/di/transportModule.test.ts, pnpm-lock.yaml
Add WebSocket connections for operations:
Operation | Pathname | Query Parameters
-- | -- | --
Genuine Check | `/genuine` | `BaseParams`
List Installed Apps | `/apps/list` | `BaseParams`
Update MCU | `/mcu` | `Omit<BaseParams, "perso"> & McuSubParams`
Update Firmware | `/install` | `BaseParams & FirmwareSubParams`
Install Apps | `/install` | `BaseParams & FirmwareSubParams & AppSubParams`
Uninstall Apps | `/install` | `BaseParams & FirmwareSubParams & AppSubParams`
Because the callbacks / listeners like: `onopen`, `onclose`, `onerror` and `onmessage` need to emit events in observables and interact with device using `sendApdu` function, they will be added in tasks. 
Add three new dependencies: `isomorphic-ws`, `ws` and `@types/ws`. The `WebSocket` object used in the code is imported from …
=> ✨ (dmk) [DSDK-489]: Add WebSocket data source

.changeset/large-mirrors-approve.md, .changeset/lemon-islands-pretend.md, packages/device-management-kit/src/api/device-action/os/GetDeviceStatus/GetDeviceStatusDeviceAction.test.ts, packages/device-management-kit/src/api/device-action/os/GoToDashboard/GoToDashboardDeviceAction.test.ts, packages/device-management-kit/src/api/device-action/os/OpenAppDeviceAction/OpenAppDeviceAction.test.ts, packages/device-management-kit/src/api/device-session/DeviceSessionState.ts, packages/device-management-kit/src/internal/device-session/model/DeviceSession.ts, packages/signer/context-module/src/shared/model/TransactionContext.ts, packages/signer/context-module/src/trusted-name/domain/TrustedNameContextLoader.test.ts, packages/signer/context-module/src/trusted-name/domain/TrustedNameContextLoader.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.test.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildEIP712ContextTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildTransactionContextTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildTransactionContextTask.ts
Nano S does not support getChallenge command, but can clear sign basic operations such as ERC20 transfert or plugins.
So we need to be able to provide non generic-parser context to the device if the command is failing.
For the sign transaction:
- If we have a Nano S, get challenge return an error, we skip it.
- The build context task will not return a domain context as the challenge is not provided
- The provide context task will be called as the Nano S does not support generic parser.
- The signTransaction task is called and data is displayed on the screen.
Also, this PR provide the `deviceModelId` to the `DeviceSession` as we need to handle the `signTransaction` differently for the `Nano S`
- **JIRA or GitHub link**: [DSDK-639]
- **Feature**:
Pull Requests must pass CI checks and …
=> 🩹 (signer-eth) [DSDK-639]: Use clear signing with Nano S

.changeset/fuzzy-eagles-cough.md, .changeset/happy-zoos-search.md, apps/sample/src/components/SignerBtcView/SignPsbtDAInputValusForm.tsx, apps/sample/src/components/SignerBtcView/index.tsx, packages/signer/signer-btc/src/api/SignerBtc.ts, packages/signer/signer-btc/src/api/app-binder/GetWalletAddressDeviceActionTypes.ts, packages/signer/signer-btc/src/api/index.ts, packages/signer/signer-btc/src/api/model/Wallet.ts, packages/signer/signer-btc/src/api/model/WalletAddressOptions.ts, packages/signer/signer-btc/src/internal/DefaultSignerBtc.ts, packages/signer/signer-btc/src/internal/app-binder/BtcAppBinder.ts, packages/signer/signer-btc/src/internal/app-binder/command/GetExtendedPublicKeyCommand.test.ts, packages/signer/signer-btc/src/internal/app-binder/command/GetWalletAddressCommand.test.ts, packages/signer/signer-btc/src/internal/app-binder/command/GetWalletAddressCommand.ts, packages/signer/signer-btc/src/internal/app-binder/device-action/GetWalletAddress/GetWalletAddressDeviceAction.test.ts, packages/signer/signer-btc/src/internal/app-binder/device-action/GetWalletAddress/GetWalletAddressDeviceAction.ts, packages/signer/signer-btc/src/internal/app-binder/task/GetWalletAddressTask.test.ts, packages/signer/signer-btc/src/internal/app-binder/task/GetWalletAddressTask.ts, packages/signer/signer-btc/src/internal/use-cases/di/useCasesModule.test.ts, packages/signer/signer-btc/src/internal/use-cases/di/useCasesModule.ts, packages/signer/signer-btc/src/internal/use-cases/di/useCasesTypes.ts, packages/signer/signer-btc/src/internal/use-cases/get-wallet-address/GetWalletAddressUseCase.test.ts, packages/signer/signer-btc/src/internal/use-cases/get-wallet-address/GetWalletAddressUseCase.ts, packages/signer/signer-btc/src/internal/utils/BtcCommandUtils.ts
Implement getWalletAddress device action
- **JIRA or GitHub link**: [DSDK-476](https://ledgerhq.atlassian.net/browse/DSDK-476)
---
[DSDK-476]: https://ledgerhq.atlassian.net/browse/DSDK-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (signer-btc) [DSDK-485]: Implement getWalletAddress device-action

packages/signer/signer-btc/README.md
Update Readme for sign psbt & sign transaction return types
- **Feature**:
---
=> :memo: (signer-btc) [NO-ISSUE]: Update signer-btc readme

apps/docs/pages/docs/explanations/signers.mdx, apps/docs/pages/docs/explanations/signers/btc.mdx, apps/docs/pages/docs/explanations/signers/eth.mdx, apps/docs/pages/docs/explanations/signers/solana.mdx, packages/signer/signer-btc/README.md, packages/signer/signer-eth/README.md, packages/signer/signer-solana/README.md
=> 📝 (docs) [NO-ISSUE]: Update docs app and signers readme

.changeset/few-colts-jump.md, packages/tools/esbuild-tools/build.mjs, packages/tools/esbuild-tools/watch.mjs, packages/transport/web-ble/src/api/transport/WebBleTransport.ts
Fix Chrome windows ble connect
Remake of #537 with rebase + CI run 
- **Feature**:
---
=> 🐛 (transport) [NO-ISSUE]: Fix Chrome windows ble connect

.changeset/cyan-seals-scream.md, apps/sample/package.json, apps/sample/src/components/SignerEthView/index.tsx, pnpm-lock.yaml
When using external wallets such as Rabby, we can sometime extract the raw transaction in JSON format
instead of serialized format. It look like:
```json
{
"chainId": 42161,
"from": "0x519192a437e6aeb895cec72828a73b11b698de3a",
"to": "0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9",
"value": "0x0",
"data": "0x095ea7b3000000000000000000000000000000000022d473030f116ddee9f6b43ac78ba3ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
"gas": "0x1fbe6",
"maxFeePerGas": "0x1036640",
"maxPriorityFeePerGas": "0x1036640",
"nonce": "0xc"
}
```
JSON transaction can be serialized by ethers, therefore it's useful to accept them in the sample app to easily
test any dapp using external crafters
- **Feature**:
Pull Requests must pass CI checks and undergo code …
=> :sparkles: (smpl) [NO-ISSUE]: Accept JSON ethereum raw transactions

apps/docs/package.json, apps/sample/package.json, pnpm-lock.yaml
This reverts commit d38c9a60c2630b49394c7edc586b0d62f726c2e2, reversing
changes made to 451131bda3313aa02a77bce9b5a958f4d64e985b.
Revert unwated nextjs update
- **Feature**:
---
=> ⏪️ (nextjs) [NO-ISSUE]: Revert next.js bump (#635)

apps/docs/package.json, apps/sample/package.json, pnpm-lock.yaml
Cherry pick the revert of nextjs update to fix sample app in production
- **Feature**:
---
=> ⏪️ (nextjs) [NO-ISSUE]: Revert next.js bump (#635) (#651)

.github/workflows/build-mobile.yml
Create workflow to build mobile app
- **Feature**:
---
=> 🚧 (ci) [NO-ISSUE]: Create dispatch workflow for mobile app build

.github/workflows/update_toolchain.yml, .github/workflows/version.yml, danger/helpers.ts
Few updates to tackle some remaining issues we had in our CI suite.
**Versioning workflow**:
The issue with the versioning workflow is that, triggering it (a push on the release branch) without new _changesets_ to consume, would fail the job. 
The proposed solution here is to allow the `action/changeset` to fail gracefully with `continue-on-error`.
Also use the token that we were given to create PR on the developer-portal (which has access to our repo as well)
**Release branch and Danger**:
The release branch contains the commit made by developers, as well as the title of the PR which does not abide to the traditional commit guidelines (the ticket number before the `:` in the title messes it up).
The proposed solution here is to update the regexp to also allow for the commit messages that …
=> 👷 (ci) [NO-ISSUE]: Improvements for a more seamless DX

.github/workflows/snapshot_release.yml
Add a default value on snapshot release on cron trigger
- **JIRA or GitHub link**: 
- **Feature**:
---
=> 💚 (snapshot) [NO-ISSUE]: Fix cron snapshot release

.changeset/violet-llamas-add.md, .changeset/violet-llamas-adder.md, .changeset/violet-llamas-addest.md, .changeset/violet-llamas-addestest.md, packages/device-management-kit/src/api/DeviceManagementKit.test.ts, packages/device-management-kit/src/api/DeviceManagementKit.ts, packages/device-management-kit/src/api/device-action/DeviceAction.ts, packages/device-management-kit/src/api/device-action/__test-utils__/makeInternalApi.ts, packages/device-management-kit/src/api/device-session/use-case/DisableDeviceSessionRefresher.test.ts, packages/device-management-kit/src/api/device-session/use-case/DisableDeviceSessionRefresher.ts, packages/device-management-kit/src/api/secure-channel/task/ConnectToSecureChannelTask.test.ts, packages/device-management-kit/src/api/secure-channel/task/ConnectToSecureChannelTask.ts, packages/device-management-kit/src/internal/device-session/di/deviceSessionModule.ts, packages/device-management-kit/src/internal/device-session/di/deviceSessionTypes.ts, packages/device-management-kit/src/internal/device-session/model/DeviceSession.ts, packages/device-management-kit/src/internal/device-session/service/RefresherService.test.ts, packages/device-management-kit/src/internal/device-session/service/RefresherService.ts, packages/signer/signer-btc/src/internal/app-binder/device-action/__test-utils__/makeInternalApi.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/__test-utils__/makeInternalApi.ts, packages/signer/signer-solana/src/internal/app-binder/device-action/__test-utils__/makeInternalApi.ts
Allow for a finer control when enabling and disabling the refresher
- **Feature**:
---
=> 👔 (refresher) [DSDK-680]: Update refresher toggling logic

apps/docs/pages/docs/explanation/_meta.js, apps/docs/pages/docs/explanation/introduction.mdx, apps/docs/pages/docs/explanation/ledgerjs.mdx, apps/docs/pages/docs/explanation/signers.mdx
In the Explanation section of the documentation, I added more context about the signers and rephrased the existing doc about LedgerJS.
[NO-ISSUE]
Not applicable because I only modified documentation.
---
=> 📝 (doc) [NO-ISSUE]: Improvement of the explanation section

.github/workflows/update_toolchain.yml
To allow the sync toolchain PR to completely work with our CI, the commit needs to be signed. 
Following what has been done on ledger live side, we use a github action to create the commit using the github api (which signs commit)
This should allow the sync_toolchain workflow to create compliant PRs to go through the CI as any others.
- **Feature**:
---
=> 👷 (signing) [NO-ISSUE]: Use github api to sign commit

.changeset/large-terms-buy.md, packages/device-management-kit/src/api/device-action/model/UserInteractionRequired.ts, packages/device-management-kit/src/api/device-action/os/ListAppsWithMetadata/ListAppsWithMetadataDeviceAction.ts, packages/device-management-kit/src/api/secure-channel/device-action/GenuineCheck/GenuineCheckDeviceAction.ts, packages/device-management-kit/src/api/secure-channel/device-action/GenuineCheck/types.ts, packages/device-management-kit/src/api/secure-channel/types.ts, packages/device-management-kit/src/internal/manager-api/data/AxiosManagerApiDataSource.test.ts, packages/device-management-kit/src/internal/manager-api/data/AxiosManagerApiDataSource.ts, packages/device-management-kit/src/internal/manager-api/data/ManagerApiDataSource.ts, packages/device-management-kit/src/internal/manager-api/data/ManagerApiDto.ts, packages/device-management-kit/src/internal/manager-api/data/__mocks__/AxiosManagerApiDataSource.ts, packages/device-management-kit/src/internal/manager-api/model/Application.ts, packages/device-management-kit/src/internal/manager-api/model/Params.ts, packages/device-management-kit/src/internal/manager-api/service/DefaultManagerApiService.test.ts, packages/device-management-kit/src/internal/manager-api/service/DefaultManagerApiService.ts, packages/device-management-kit/src/internal/manager-api/service/ManagerApiService.ts
- Add `getAppList` HTTP request in manager API;
- Adapt manger API in order to have a better structure.
- Update the service `getAppsByHash` parameter to `hashes: string[]` because the hashes are not always come from the `ListAppsCommand` response, they need to be extracted in concrete use case.   
- **Feature**:
---
=> ✨ (dmk) [NO-ISSUE]: Add get app list HTTP request

apps/docs/pages/docs/getting-started.mdx
I added the video presentation of the DMK in the Getting Started page.
[NO-ISSUE]
Not applicable as I only modified documentation.
---
=> 📝 (doc) [NO-ISSUE]: DMK video presentation

.changeset/shiny-mails-decide.md, packages/device-management-kit/src/internal/device-session/model/DeviceSession.ts, packages/device-management-kit/src/internal/device-session/model/DeviceSessionRefresher.test.ts, packages/device-management-kit/src/internal/device-session/model/DeviceSessionRefresher.ts, packages/device-management-kit/src/internal/discovery/use-case/ConnectUseCase.test.ts, packages/device-management-kit/src/internal/discovery/use-case/ConnectUseCase.ts
=> :bug: (dmk) [NO-ISSUE]: Ensure device session is ready after device connection

.changeset/heavy-flies-tap.md, apps/sample/src/providers/SignerEthProvider/index.tsx, packages/signer/context-module/src/ContextModuleBuilder.ts
Update transaction check backend url.
- **Feature**:
---
=> 🧱 (context-module) [DSDK-699]: Update transaction check backend url

packages/flipper-plugin-client/package.json, packages/flipper-plugin-client/src/FlipperPluginManager.ts, pnpm-lock.yaml
- Changed the plugin id so it matches with the desktop plugin, otherwise it does not work (it was renamed a while ago when renaming all "device-sdk" to "dmk", so it broke).
- Updated the js-flipper dep.
- **Feature**:
---
=> 🐛 (flipper-plugin) [NO-ISSUE]: Fix plugin ID & bump js-flipper dep

.changeset/hungry-plums-allow.md, apps/docs/pages/docs/references/signers/eth.mdx, packages/signer/signer-eth/README.md, packages/signer/signer-eth/src/api/app-binder/SignTransactionDeviceActionTypes.ts, packages/signer/signer-eth/src/api/app-binder/SignTypedDataDeviceActionTypes.ts, packages/signer/signer-eth/src/api/index.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.test.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTypedData/SignTypedDataDeviceAction.test.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTypedData/SignTypedDataDeviceAction.ts
Add current step in intermediateValue for complex DA 'SignTransactionDeviceAction' and 'SignTypedDataDeviceAction`. The idea is to return the current step to the consumer to be able to display more information on the screen, for example a loader during the 'BUILD_CONTEXT'.
https://github.com/user-attachments/assets/78da5356-0906-4116-9370-8312c7969980
- **Feature**:
---
=> 👔 (signer-eth) [DSDK-697]: Add current step in intermediateValue for complex DA

apps/docs/pages/docs/beginner/_meta.js, apps/docs/pages/docs/beginner/ble_flex_stax.mdx, apps/docs/pages/docs/references/identifiers.mdx
- Added the identifiers in the reference section
- Added short documentation in the beginners section to explain how to add BLE and USB transport for Flex and Stax
[NO-ISSUE] 
Not applicable, only documentation was modified.
---
=> 📝 (doc) [NO-ISSUE]: Identifiers documentation

.changeset/eight-glasses-clean.md, apps/sample/src/components/DeviceActionsView/AllDeviceActions.tsx, packages/device-management-kit/src/api/device-action/__test-utils__/setupTestMachine.ts, packages/device-management-kit/src/api/index.ts, packages/device-management-kit/src/api/secure-channel/device-action/GenuineCheck/GenuineCheckDeviceAction.ts, packages/device-management-kit/src/api/secure-channel/device-action/InstallApp/InstallAppDeviceAction.test.ts, packages/device-management-kit/src/api/secure-channel/device-action/InstallApp/InstallAppDeviceAction.ts, packages/device-management-kit/src/api/secure-channel/device-action/InstallApp/types.ts, packages/device-management-kit/src/api/secure-channel/device-action/ListInstalledApps/ListInstalledAppsDeviceAction.ts, packages/device-management-kit/src/api/secure-channel/device-action/ListInstalledApps/types.ts, packages/device-management-kit/src/api/secure-channel/device-action/UninstallApp/UninstallAppDeviceAction.test.ts, packages/device-management-kit/src/api/secure-channel/device-action/UninstallApp/UninstallAppDeviceAction.ts, packages/device-management-kit/src/api/secure-channel/device-action/UninstallApp/types.ts, packages/device-management-kit/src/api/secure-channel/utils.test.ts, packages/device-management-kit/src/api/transport/model/TransportConnectedDevice.test.ts, packages/device-management-kit/src/api/types.ts, packages/device-management-kit/src/internal/manager-api/data/AxiosManagerApiDataSource.test.ts, packages/device-management-kit/src/internal/secure-channel/data/DefaultSecureChannelDataSource.test.ts, packages/device-management-kit/src/internal/secure-channel/model/Params.ts, packages/device-management-kit/src/internal/secure-channel/service/DefaultSecureChannelService.test.ts, packages/device-management-kit/src/internal/secure-channel/service/DefaultSecureChannelService.ts, packages/device-management-kit/src/internal/secure-channel/service/SecureChannelService.ts
- Add `InstallAppDeviceAction` that allows users to install an app on the device by name;
- Add `UninstallAppDeviceAction` that allows users to uninstall an installed app on the device by name;
- Update secure channel service to adjust real use case.
https://github.com/user-attachments/assets/721d053a-21c3-4c33-b8e9-552a97adb546
Tests on the way...
- **Feature**:
- Users can install an app on the device;
- Users can uninstall an app on the device.
---
=> ✨ (dmk) [NO-ISSUE]: Add install and uninstall app device actions

apps/docs/pages/docs/beginner/_meta.js, apps/docs/pages/docs/beginner/discover_and_connect.mdx, apps/docs/pages/docs/beginner/exchange_data.mdx, apps/docs/pages/docs/beginner/init_dmk.mdx, apps/docs/pages/docs/beginner/setup.mdx
I updated the tutorials in the "beginners' guides" section. It's the same content, but with a more ditactic content.
[NO-ISSUE] 
Not relevant because it is only documentation.
---
=> 📝 (doc) [NO-ISSUE]: Beginners guides improvement

apps/docs/pages/docs/beginner/discover_and_connect.mdx, packages/device-management-kit/README.md
updated docs 
- **Feature**:
---
=> 📝 (docs) [NO-ISSUE]: Updating docs for DMK changes (connect useCase)

.changeset/fair-garlics-brake.md, packages/signer/signer-eth/src/api/app-binder/SignTransactionDeviceActionTypes.ts, packages/signer/signer-eth/src/api/app-binder/SignTypedDataDeviceActionTypes.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.test.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTypedData/SignTypedDataDeviceAction.test.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTypedData/SignTypedDataDeviceAction.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildEIP712ContextTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildEIP712ContextTask.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildTransactionContextTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildTransactionContextTask.ts, packages/signer/signer-eth/src/internal/shared/utils/ApplicationChecker.test.ts, packages/signer/signer-eth/src/internal/shared/utils/ApplicationChecker.ts
PLusing don't have the same version as Ethereum application.
That version is used to detect features support, for backward compatibility.
- **Feature**:
---
=> :bug: (signer-eth) [NO-ISSUE]: Fix version compatibility checker for plugins

packages/tools/ldmk-cli/release.cjs
To make sure the lockfile is up to date, run `pnpm i` during the **enter-release** and **exit-release** scripts
thanks @aussedatlo for the catch
- **Feature**:
---
=> 🔨 (cli) [NO-ISSUE]: Release scripts to run `pnpm i` now

apps/docs/tsconfig.json, apps/sample/tsconfig.json, packages/config/typescript/tsconfig.sdk.json, packages/config/typescript/tsconfig.web.json, packages/device-management-kit/src/api/device-model/data/StaticDeviceModelDataSource.ts, packages/device-management-kit/tsconfig.json, packages/flipper-plugin-client/tsconfig.json, packages/mockserver-client/tsconfig.json, packages/signer/context-module/src/transaction/data/HttpTransactionDataSource.ts, packages/signer/context-module/src/typed-data/data/HttpTypedDataDataSource.ts, packages/signer/context-module/tsconfig.json, packages/signer/signer-btc/tsconfig.json, packages/signer/signer-eth/tsconfig.json, packages/signer/signer-solana/tsconfig.json, packages/signer/signer-utils/tsconfig.json, packages/transport/mockserver/tsconfig.json, packages/transport/web-ble/tsconfig.json, packages/transport/web-hid/tsconfig.json, packages/trusted-apps/tsconfig.json, packages/ui/tsconfig.json
=> 👷 (tsconfig) [NO-ISSUE]: Change from esnext to es2022

.changeset/plenty-roses-push.md, apps/sample/src/components/CalView/AppProviderDrawer.tsx, apps/sample/src/components/CalView/index.tsx, packages/device-management-kit/README.md, packages/device-management-kit/src/api/DeviceManagementKit.ts, packages/device-management-kit/src/internal/manager-api/data/AxiosManagerApiDataSource.test.ts, packages/device-management-kit/src/internal/manager-api/data/AxiosManagerApiDataSource.ts, packages/device-management-kit/src/internal/manager-api/data/ManagerApiDataSource.ts, packages/device-management-kit/src/internal/manager-api/data/__mocks__/AxiosManagerApiDataSource.ts
- Added the option to set a custom provider in sample app 
- Added `getProvider` to DMK to get current value (as provider can now be set at build or run time) 
https://github.com/user-attachments/assets/bb3c345c-a7b0-4e5e-8d51-d9e3e3b844fa
- **JIRA or GitHub link**: [DSDK-718](https://ledgerhq.atlassian.net/browse/DSDK-718)
- **Feature**:
---
[DSDK-718]: https://ledgerhq.atlassian.net/browse/DSDK-718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (sample-dmk) [DSDK-718]: Add set provider option to sample app

.github/workflows/update_toolchain.yml
Add dedupe step in update_toolchain workflow + force push branch on creation in case the previous one is still present
- **JIRA or GitHub link**: [DSDK-727]
- **Feature**:
---
[DSDK-727]: https://ledgerhq.atlassian.net/browse/DSDK-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 🩺 (toolchain) [DSDK-727]: Dedupe + force push in toolchain update workflow

apps/docs/pages/docs/integration/how_to/transports.mdx, packages/transport/rn-ble/README.md, packages/transport/rn-ble/package.json, packages/transport/web-ble/README.md, packages/transport/web-hid/README.md
Add react-native-ble package readme
- **JIRA or GitHub link**: [DSDK-735]
- **Feature**:
---
[DSDK-735]: https://ledgerhq.atlassian.net/browse/DSDK-735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 📝 (rnble) [DSDK-735]: Add readme

.changeset/config.json
Restore github config for changeset
- **Feature**: [NO-ISSUE]
---
=> 🔧 (release) [NO-ISSUE]: Restore github config for changeset

.changeset/weak-cobras-study.md, packages/device-management-kit/src/api/transport/model/Transport.ts, packages/device-management-kit/src/internal/discovery/use-case/StopDiscoveringUseCase.test.ts, packages/device-management-kit/src/internal/discovery/use-case/StopDiscoveringUseCase.ts
The Transport interface declared stopDiscovering as a synchronous function, but the implementation of the RNBleTransport actually taught us that some stopDiscovering could be async.
This PR aims to fix the type of stopDiscovering and updates the use case to be async as well
- **Feature**:
---
=> 🐛 (dmk) [NO-ISSUE]: Transport.stopDiscovering to allow for promises

.github/workflows/update_toolchain.yml
- **!drop**
- **🔨 (update-toolchain): Make sure the changes are correctly applied**
Small adjustements to make update toolchain work correctly
- **Feature**:
---
=> 🔨 (update-toolchain) [NO-ISSUE]: Make sure the changes are correctly applied

.changeset/friendly-houses-marry.md, apps/docs/pages/docs/beginner/exchange_data.mdx, apps/docs/pages/docs/integration/how_to/dmk.mdx, packages/device-management-kit/README.md, packages/device-management-kit/src/api/command/use-case/SendCommandUseCase.ts, packages/device-management-kit/src/api/device-action/DeviceAction.ts, packages/device-management-kit/src/internal/device-session/data/ApduResponseConst.ts, packages/device-management-kit/src/internal/device-session/model/DevicePinger.ts, packages/device-management-kit/src/internal/device-session/model/DeviceSession.ts, packages/device-management-kit/src/internal/device-session/model/DeviceSessionStateHandler.test.ts, packages/device-management-kit/src/internal/device-session/model/DeviceSessionStateHandler.ts
The sendCommand method from device session now accepts an abortTimeout (so the pinger cannot "block" the message exchange).
Added the argument to the SendCommandUseCase
The pinger (refresher) now times out after 800ms 
- **Feature**:
---
=> 👔 (dmk) [NO-ISSUE]: SendCommand now accepts an abortTimeout argument

apps/mobile/src/components/DeviceActions.tsx
Add install app DA with secure channel in mobile sample app
- **Feature**:
---
=> 💄 (mobile) [NO-ISSUE]: Add install app DA 

.changeset/sixty-insects-fix.md, packages/transport/rn-ble/src/api/transport/RNBleTransport.ts
Patched connection and reconnection
- **Feature**:
---
=> 🐛 (ble-transport) [DSDK-750]: Patch reconnection error

packages/device-management-kit/src/internal/device-session/model/Frame.ts, packages/transport/rn-hid/android/src/main/kotlin/com/ledger/devicesdk/shared/internal/transport/framer/FramerService.kt
=> 🐛 (rn-hid) [NO-ISSUE]: Fix framing for RN HID transport

.changeset/mighty-oranges-reflect.md, packages/signer/signer-eth/src/api/app-binder/SignTransactionDeviceActionTypes.ts, packages/signer/signer-eth/src/api/app-binder/SignTypedDataDeviceActionTypes.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.test.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTypedData/SignTypedDataDeviceAction.test.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTypedData/SignTypedDataDeviceAction.ts
Add result value for tc opt-in.
As `assign` does not automatically create a snapshot, I added a specific step combined with `after` that will force a new snapshot with the opt in result value.
- **JIRA or GitHub link**: [NO-ISSUE] 
- **Feature**:
---
=> 🚸 (signer-eth) [NO-ISSUE]: Add result value for tc opt-in

.changeset/fifty-maps-confess.md, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTypedData/SignTypedDataDeviceAction.test.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTypedData/SignTypedDataDeviceAction.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildEIP712ContextTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildEIP712ContextTask.ts, packages/signer/signer-eth/src/internal/app-binder/task/ProvideEIP712ContextTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/ProvideEIP712ContextTask.ts, packages/signer/signer-eth/src/internal/app-binder/task/SignTypedDataLegacyTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/SignTypedDataLegacyTask.ts
…arser limitations
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/DSDK-757
- **Feature**:
---
=> :bug: (signer-eth) [DSDK-757]: Avoid SignTypedData flows failure due to ethers parser limitations

.changeset/warm-panthers-whisper.md, packages/signer/signer-eth/src/internal/typed-data/service/DefaultTypedDataParserService.ts, packages/signer/signer-eth/src/internal/typed-data/service/TypedDataParser.test.ts, packages/signer/signer-eth/src/internal/typed-data/service/TypedDataParser.ts
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/DSDK-758
- **Feature**:
---
=> :bug: (signer-eth) [DSDK-758]: Add EIP712 default domain types if missing from typed message

packages/transport/rn-ble/src/api/transport/RNBleApduSender.ts
Change the way of selecting the write characteristic, on old OS we need to use the WriteWithResponse characteristic. 
Tested on Nano X: 2.0.1 OS version (Install app and open app device action ✅)
[DSDK-760](https://ledgerhq.atlassian.net/browse/DSDK-760)
- **Feature**:
---
[DSDK-760]: https://ledgerhq.atlassian.net/browse/DSDK-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 🐛 (rn-ble) [DSDK-760]: Fix ble connection on NanoX old OS version

packages/tools/ldmk-tool/release.cjs
Handle a specific case where `dependencies` or `peerDependencies` from package.json is not defined
- **Feature**:
---
=> 🐛 (ldmk-tool) [NO-ISSUE]: Handle cases where `deps` and `peerDeps` are not defined

pnpm-lock.yaml, pnpm-workspace.yaml
Bump eslint group
fixes: #842
- **Feature**:
---
=> ⬆️ (eslint) [NO-ISSUE]: Bump eslint group

.changeset/honest-ties-dream.md, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTypedData/SignTypedDataDeviceAction.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildTransactionContextTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildTransactionContextTask.ts
=> :bug: (signer-eth) [NO-ISSUE]: GetChallenge is not supported on Nano S

.changeset/quiet-fans-promise.md, apps/sample/src/components/SignerEthView/index.tsx, packages/device-management-kit/src/api/apdu/utils/ByteArrayBuilder.test.ts, packages/device-management-kit/src/api/apdu/utils/ByteArrayBuilder.ts, packages/device-management-kit/src/api/device-action/model/UserInteractionRequired.ts, packages/signer/signer-eth/src/api/SignerEth.ts, packages/signer/signer-eth/src/api/app-binder/SignDelegationAuthorizationTypes.ts, packages/signer/signer-eth/src/api/index.ts, packages/signer/signer-eth/src/internal/DefaultSignerEth.test.ts, packages/signer/signer-eth/src/internal/DefaultSignerEth.ts, packages/signer/signer-eth/src/internal/app-binder/EthAppBinder.test.ts, packages/signer/signer-eth/src/internal/app-binder/EthAppBinder.ts, packages/signer/signer-eth/src/internal/app-binder/command/SignAuthorizationDelegationCommand.test.ts, packages/signer/signer-eth/src/internal/app-binder/command/SignAuthorizationDelegationCommand.ts, packages/signer/signer-eth/src/internal/app-binder/task/SendSignAuthorizationDelegationTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/SendSignAuthorizationDelegationTask.ts, packages/signer/signer-eth/src/internal/di.ts, packages/signer/signer-eth/src/internal/eip7702/di/eip7702Module.test.ts, packages/signer/signer-eth/src/internal/eip7702/di/eip7702Module.ts, packages/signer/signer-eth/src/internal/eip7702/di/eip7702Types.ts, packages/signer/signer-eth/src/internal/eip7702/use-case/SignDelegationAuthorizationUseCase.test.ts, packages/signer/signer-eth/src/internal/eip7702/use-case/SignDelegationAuthorizationUseCase.ts, pnpm-lock.yaml, pnpm-workspace.yaml
=> :sparkles: (signer-eth) [NO-ISSUE]: Add new API for EIP7702 in signer kit ETH

pnpm-lock.yaml, pnpm-workspace.yaml
Bump eslint and changesets in catalogs
- **Feature**:
---
=> ⬆️ (dependencies) [NO-ISSUE]: Bump eslint and changeset

.changeset/eight-lions-enjoy.md, packages/device-management-kit/src/api/device-action/os/InstallOrUpdateApps/types.ts, packages/device-management-kit/src/api/device-action/task/BuildAppsInstallPlanTask.test.ts, packages/device-management-kit/src/api/device-action/task/BuildAppsInstallPlanTask.ts
Bug reproduces in Ledger Live when device firmware is outdated, and a minVersion is selected for an installed app (that is not found in provider for that outdated firmware)
- **Feature**:
---
=> :bug: (dmk) [NO-ISSUE]: Should throw an error when app minVersion is not found in catalog

apps/docs/pages/docs/getting-started.mdx
There are typos in the npm names of the packages in the package list
Comes from a PR on the Developer Portal concerning the contents of the device-sdk-ts repo
https://github.com/LedgerHQ/developer-portal/pull/434
- **Feature**:
---
=> 📝 (doc) [NO-ISSUE]: Typo NPM names

.changeset/unlucky-singers-march.md, packages/device-management-kit/src/api/transport/model/DeviceConnectionStateMachine.test.ts
I tried to reproduce that bug using unit tests: https://ledgerhq.atlassian.net/browse/LIVE-19429
but finally there was no bug and the state machine worked well :sweat_smile: 
- **Feature**:
---
=> :white_check_mark: (dmk) [NO-ISSUE]: Add unit tests for DeviceConnection state machine

.changeset/eighty-numbers-nail.md, packages/signer/signer-eth/src/internal/app-binder/command/ProvideProxyInfoCommand.test.ts, packages/signer/signer-eth/src/internal/app-binder/command/ProvideProxyInfoCommand.ts
Add ProvideProxyInfoCommand
- **JIRA or GitHub link**: [DSDK-809]
- **Feature**:
---
[DSDK-809]: https://ledgerhq.atlassian.net/browse/DSDK-809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (signer-eth) [DSDK-809]: Add ProvideProxyInfoCommand

.changeset/two-lamps-end.md, apps/sample/src/components/CalView/MetadataServiceDrawer.tsx, apps/sample/src/components/CalView/index.tsx, apps/sample/src/providers/SignerEthProvider/index.tsx, packages/signer/context-module/src/ContextModuleBuilder.test.ts, packages/signer/context-module/src/ContextModuleBuilder.ts, packages/signer/context-module/src/DefaultContextModule.test.ts, packages/signer/context-module/src/config/model/ContextModuleConfig.ts, packages/signer/context-module/src/nft/data/HttpNftDataSource.test.ts, packages/signer/context-module/src/nft/data/HttpNftDataSource.ts, packages/signer/context-module/src/transaction/data/HttpProxyDataSource.test.ts, packages/signer/context-module/src/transaction/data/HttpProxyDataSource.ts, packages/signer/context-module/src/transaction/data/ProxyDelegateCallDto.ts, packages/signer/context-module/src/transaction/data/ProxyImplementationAddressDto.ts, packages/signer/context-module/src/transaction/di/transactionModuleFactory.ts, packages/signer/context-module/src/transaction/di/transactionTypes.ts, packages/signer/context-module/src/transaction/model/ProxyDelegateCall.ts, packages/signer/context-module/src/transaction/model/ProxyImplementationAddress.ts, packages/signer/context-module/src/trusted-name/data/HttpTrustedNameDataSource.test.ts, packages/signer/context-module/src/trusted-name/data/HttpTrustedNameDataSource.ts
- Add proxy metadata datasource to get proxy delegate call and implementation address from the metadata backend
- Change some context module builder api naming for more clarity
- `addCalConfig` -> `setCalConfig`
-  `addWeb3ChecksConfig` ->`setWeb3ChecksConfig`
- Use an injected config parameter for the metadata backend url instead of a hardcoded one
- **JIRA or GitHub link**: [DSDK-810]
- **Feature**:
---
[DSDK-810]: https://ledgerhq.atlassian.net/browse/DSDK-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (context-module) [DSDK-810]: Add proxy metadata datasource

.github/pull_request_template_release.md
Add release PR template
- **Feature**:
---
=> 🔧 (release) [NO-ISSUE]: Add release PR template

.changeset/petite-lemons-rhyme.md, packages/signer/signer-solana/src/internal/app-binder/services/TransactionInspector.test.ts, packages/signer/signer-solana/src/internal/app-binder/services/TransactionInspector.ts
Polished TransactionInspector logic
- **Feature**:
---
=> 🎨 (solana-signer) [NO-ISSUE]: Polish TransactionInspector

.changeset/khaki-cooks-smoke.md, apps/sample/src/components/SignerSolanaView/index.tsx, packages/signer/signer-solana/src/api/SolanaTools.ts, packages/signer/signer-solana/src/api/SolanaToolsBuilder.ts, packages/signer/signer-solana/src/api/app-binder/GenerateTransactionDeviceActionTypes.ts, packages/signer/signer-solana/src/api/index.ts, packages/signer/signer-solana/src/internal/DefaultSolanaTools.test.ts, packages/signer/signer-solana/src/internal/DefaultSolanaTools.ts, packages/signer/signer-solana/src/internal/app-binder/SolanaAppBinder.test.ts, packages/signer/signer-solana/src/internal/app-binder/SolanaAppBinder.ts, packages/signer/signer-solana/src/internal/app-binder/command/GetPubKeyCommand.ts, packages/signer/signer-solana/src/internal/app-binder/device-action/GenerateTransactionDeviceAction.ts, packages/signer/signer-solana/src/internal/app-binder/device-action/SignTransactionDeviceAction.ts, packages/signer/signer-solana/src/internal/app-binder/services/GenerateSolanaTransaction.test.ts, packages/signer/signer-solana/src/internal/app-binder/services/GenerateSolanaTransaction.ts, packages/signer/signer-solana/src/internal/use-cases/di/useCasesModule.test.ts, packages/signer/signer-solana/src/internal/use-cases/di/useCasesModule.ts, packages/signer/signer-solana/src/internal/use-cases/di/useCasesTypes.ts, packages/signer/signer-solana/src/internal/use-cases/generateTransaction/GenerateTransactionUseCase.test.ts, packages/signer/signer-solana/src/internal/use-cases/generateTransaction/GenerateTransactionUseCase.ts
Added a solana transaction generator to test Solana signer
- **JIRA or GitHub link**: [DSDK-850](https://ledgerhq.atlassian.net/browse/DSDK-850)
- **Feature**:
---
[DSDK-850]: https://ledgerhq.atlassian.net/browse/DSDK-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (signer-solana) [DSDK-850]: Add GenerateTransactionDeviceAction

apps/sample/src/app/device-actions/page.tsx, apps/sample/src/app/signer/bitcoin/page.tsx, apps/sample/src/app/signer/ethereum/page.tsx, apps/sample/src/app/signer/solana/page.tsx, apps/sample/src/components/SessionIdWrapper.tsx, pnpm-lock.yaml, pnpm-workspace.yaml
=> ⏪ (smpl) [NO-ISSUE]: Revert next update

.changeset/blue-tables-hammer.md, packages/trusted-apps/ledger-keyring-protocol/src/api/app-binder/GetSeedIdCommandTypes.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/command/GetSeedIdCommand.test.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/command/GetSeedIdCommand.ts
[DOC](https://github.com/LedgerHQ/app-ledger-sync/blob/develop/doc/COMMANDS.md#get_seed_id)
The challenge TLV will come from `LKRPDataSource.getChallenge` as string so it can be passed directly to this command (no need to parse it).
- **JIRA or GitHub link**: [DSDK-841]
- **Feature**:
---
[DSDK-841]: https://ledgerhq.atlassian.net/browse/DSDK-841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ✨ (keyring) [DSDK-841]: Implement the GET_SEED_ID command

.changeset/shiny-spoons-talk.md, apps/sample/src/components/LedgerKeyringProtocolView/index.tsx, apps/sample/src/providers/LedgerKeyringProvider/index.tsx, packages/trusted-apps/ledger-keyring-protocol/package.json, packages/trusted-apps/ledger-keyring-protocol/src/api/LedgerKeyringProtocol.ts, packages/trusted-apps/ledger-keyring-protocol/src/api/LedgerKeyringProtocolBuilder.ts, packages/trusted-apps/ledger-keyring-protocol/src/api/app-binder/AuthenticateDeviceActionTypes.ts, packages/trusted-apps/ledger-keyring-protocol/src/api/app-binder/Errors.ts, packages/trusted-apps/ledger-keyring-protocol/src/api/index.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/DefaultLedgerKeyringProtocol.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/LedgerKeyringProtocolBinder.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/command/utils/ledgerKeyringProtocolErrors.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/device-action/AuthenticateDeviceAction.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/device-action/utils/raiseAndAssign.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/task/SignChallengeWithDeviceTask.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/di.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/lkrp-datasource/data/HttpLKRPDataSource.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/lkrp-datasource/data/LKRPDataSource.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/use-cases/authentication/AuthenticateUseCase.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/use-cases/di/useCasesModule.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/use-cases/di/useCasesTypes.ts, pnpm-lock.yaml
This PR implement the device authentication and setup the authenticate device action, usecase, and the sample app section. This is all so that the authentication could actually be tested:
https://device-sdk-ts-sample-git-feat-dsdk-827-lkrp-deviceauth-ledgerhq.vercel.app/trusted-apps/ledger-sync
https://github.com/user-attachments/assets/c8a9eed0-c583-44bb-82d4-c6480bd5078c
Apart from this PR also introduce an xstate action helper called `raiseAndAssign` which avoid having a separate state to check errors every time an actor might fail.
- **JIRA or GitHub link**: [DSDK-827]
- **Feature**:
---
[DSDK-827]: …
=> ✨ (keyring) [DSDK-827]: Implement LKRP device authentication

.changeset/empty-berries-repair.md, packages/trusted-apps/ledger-keyring-protocol/src/api/app-binder/GetEncryptionKeyDeviceActionTypes.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/device-action/AuthenticateDeviceAction.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/device-action/GetEncryptionKeyDeviceAction.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/device-action/utils/required.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/task/SignChallengeWithKeypairTask.test.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/task/SignChallengeWithKeypairTask.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/utils/LKRPBlockStream.ts
Initialize the device action which ultimately should extract the encryption key (and add the member to the trustchain if necessary).
Only implemented states:
- `GetTrustchain`
- `OpenApp`
- `CheckApplicationStreamExist`
https://github.com/user-attachments/assets/a384346d-0ee9-49e0-add1-ee8ba8b5a908
`CheckIsMembers` should not change but `LKRPBlockStream.hasMember` needs to be actually implemented.
`GetEncryptionKeyDeviceAction` was also integrated in the `AuthenticateDeviceAction` and some changes where made to allow charting the device actions with the VSCode extension:
- **JIRA or GitHub link**: [DSDK-873]
- **Feature**:
---
=> ✨ (keyring) [DSDK-873]: Initialize GetEncryptionKeyDeviceAction

.changeset/fast-geese-beg.md, apps/sample/src/providers/SignerEthProvider/index.tsx, danger/helpers.ts, packages/signer/context-module/src/ContextModuleBuilder.ts, packages/signer/context-module/src/nft/data/HttpNftDataSource.ts
=> 🐛 (clear-signing) [NO-ISSUE]: Fix NFT clear signing

.changeset/big-mayflies-clap.md, packages/signer/signer-solana/src/internal/app-binder/task/SendSignMessageTask.test.ts, packages/signer/signer-solana/src/internal/app-binder/task/SendSignMessageTask.ts
- Fixed Error 6A81 when signing messages 
- Blocked signing of empty messages 
- **JIRA or GitHub link**: [DSDK-866](https://ledgerhq.atlassian.net/browse/DSDK-866), [DSDK-807](https://ledgerhq.atlassian.net/browse/DSDK-807)
- **Feature**:
---
[DSDK-866]: https://ledgerhq.atlassian.net/browse/DSDK-866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DSDK-807]: https://ledgerhq.atlassian.net/browse/DSDK-807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 🐛 (solana-signer) [DSDK-866]: Fix error 6A81 in signOffChainMsg

.changeset/neat-gifts-bathe.md, apps/sample/src/components/LedgerKeyringProtocolView/index.tsx, packages/trusted-apps/ledger-keyring-protocol/src/internal/DefaultLedgerKeyringProtocol.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/use-cases/authentication/DecryptDataUseCase.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/use-cases/authentication/EncryptDataUseCase.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/use-cases/di/useCasesModule.ts, packages/trusted-apps/ledger-keyring-protocol/src/internal/use-cases/di/useCasesTypes.ts
Move encryptData and decryptData implems in usecases and add these to the sample app:
https://github.com/user-attachments/assets/af104458-8d1d-43e6-aa61-494e8e920b8e
- **Feature**:
---
=> 🎨 (keyring) [NO-ISSUE]: Finalize encrypt/decrypt usecases

.changeset/breezy-emus-stay.md, packages/transport/speculos/src/api/SpeculosTransport.ts, packages/transport/speculos/src/internal/datasource/HttpSpeculosDatasource.ts, packages/transport/speculos/src/internal/datasource/SpeculosDatasource.ts
the B0010000 sent to check the speculos instance was returning something when the device is waiting for a user interaction, breaking the observable flow
the B0010000 sent to check the speculos instance was returning something when the device is waiting for a user interaction, breaking the observable flow
replaced the server check with a GET /events api call
- **Feature**:
---
=> 🐛 (speculos) [NO-ISSUE]: Fix disconnection during device interactions

apps/mobile/ios/Podfile.lock
=> ⬆️ (sample) [NO-ISSUE]: Update iOS Podfile.lock

.changeset/loose-owls-study.md, packages/signer/signer-eth/src/api/index.ts
Add missing imports for eth signer Device Actions
- **Feature**:
---
=> 🐛 (signer-eth) [NO-ISSUE]: Fix DA export type

.changeset/yellow-masks-hunt.md, packages/signer/signer-eth/src/api/app-binder/SignTransactionDeviceActionTypes.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.test.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.ts
If signTransaction fails with EIP-7730, we should retry using blind signing by calling signTransaction again, but with a basic clear signing type instead of EIP-7730.
- **JIRA or GitHub link**: [DSDK-893]
- **Feature**:
---
[DSDK-893]: https://ledgerhq.atlassian.net/browse/DSDK-893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ♻️ (signer-eth) [DSDK-893]: Fallback to blind sign if needed

.changeset/plain-hoops-care.md, packages/signer/signer-eth/src/internal/app-binder/task/BuildFullContextsTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildFullContextsTask.ts
Nested contexts APDU order has changed in Ethereum application in order to optimize memory usage
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/DSDK-897
- **Feature**:
---
=> :sparkles: (signer-eth) [DSDK-897]: Re-order APDUs for provided nested contexts

.changeset/cuddly-mangos-bake.md, .changeset/old-shoes-relate.md, .changeset/purple-bears-win.md, packages/signer/context-module/src/ContextModule.ts, packages/signer/context-module/src/ContextModuleBuilder.test.ts, packages/signer/context-module/src/DefaultContextModule.test.ts, packages/signer/context-module/src/DefaultContextModule.ts, packages/signer/context-module/src/calldata/domain/CalldataContextLoader.test.ts, packages/signer/context-module/src/calldata/domain/CalldataContextLoader.ts, packages/signer/context-module/src/dynamic-network/domain/DynamicNetworkContextLoader.test.ts, packages/signer/context-module/src/dynamic-network/domain/DynamicNetworkContextLoader.ts, packages/signer/context-module/src/external-plugin/domain/ExternalPluginContextLoader.test.ts, packages/signer/context-module/src/external-plugin/domain/ExternalPluginContextLoader.ts, packages/signer/context-module/src/index.ts, packages/signer/context-module/src/nft/domain/NftContextLoader.test.ts, packages/signer/context-module/src/nft/domain/NftContextLoader.ts, packages/signer/context-module/src/shared/domain/ContextLoader.ts, packages/signer/context-module/src/shared/model/TransactionContext.ts, packages/signer/context-module/src/token/domain/TokenContextLoader.test.ts, packages/signer/context-module/src/token/domain/TokenContextLoader.ts, packages/signer/context-module/src/trusted-name/domain/TrustedNameContextLoader.test.ts, packages/signer/context-module/src/trusted-name/domain/TrustedNameContextLoader.ts, packages/signer/context-module/src/uniswap/domain/UniswapContextLoader.test.ts, packages/signer/context-module/src/uniswap/domain/UniswapContextLoader.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildBaseContexts.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildBaseContexts.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildFullContextsTask.ts
- **JIRA or GitHub link**: [DSDK-901]
- **Feature**:
---
[DSDK-901]: https://ledgerhq.atlassian.net/browse/DSDK-901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ⚡️ (signer-eth) [DSDK-901]: Filter contexts for nested calls

.changeset/bitter-nights-grin.md, .changeset/forty-cows-poke.md, packages/signer/context-module/src/trusted-name/data/HttpTrustedNameDataSource.test.ts, packages/signer/context-module/src/trusted-name/data/HttpTrustedNameDataSource.ts, packages/signer/context-module/src/trusted-name/data/TrustedNameDataSource.ts, packages/signer/context-module/src/trusted-name/data/TrustedNameDto.ts, packages/signer/context-module/src/trusted-name/domain/TrustedNameContextFieldLoader.test.ts, packages/signer/context-module/src/trusted-name/domain/TrustedNameContextFieldLoader.ts, packages/signer/context-module/src/trusted-name/domain/TrustedNameContextLoader.test.ts, packages/signer/context-module/src/trusted-name/domain/TrustedNameContextLoader.ts, packages/signer/signer-eth/src/internal/app-binder/device-action/SignTypedData/SignTypedDataDeviceAction.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildEIP712ContextTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildEIP712ContextTask.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildSubcontextsTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/BuildSubcontextsTask.ts, packages/signer/signer-eth/src/internal/app-binder/task/ProvideEIP712ContextTask.test.ts, packages/signer/signer-eth/src/internal/app-binder/task/ProvideEIP712ContextTask.ts
=> :bug: (context-module) [NO-ISSUE]: Retrieve certificate for trusted names
