LedgerHQ/device-sdk-ts

.changeset/twelve-stingrays-shake.md
packages/core/src/internal/config/data/LocalConfigDataSource.test.ts
packages/signer/keyring-eth/src/internal/app-binder/task/ProvideEIP712ContextTask.test.ts
packages/signer/keyring-eth/src/internal/app-binder/task/ProvideEIP712ContextTask.ts

When providing EIP712 domain implementations, we should early return whenever an APDU returns an error, because it invalidates the whole flow on device side.
- **Feature**:
---

:bug: (keyring-eth) [NO-ISSUE]: Early return when EIP712 Domain fails to be sent

---

.changeset/twelve-nails-allow.md
packages/core/src/internal/usb/data/UsbHidConfig.ts
packages/core/src/internal/usb/model/Errors.ts
packages/core/src/internal/usb/model/HidDevice.stub.ts
packages/core/src/internal/usb/service/UsbHidDeviceConnectionFactory.ts
packages/core/src/internal/usb/transport/UsbHidDeviceConnection.test.ts
packages/core/src/internal/usb/transport/UsbHidDeviceConnection.ts
packages/core/src/internal/usb/transport/WebUsbHidTransport.test.ts
packages/core/src/internal/usb/transport/WebUsbHidTransport.ts

- `sendApdu`: it will now wait for a reconnection (or timeout) in case the connection has been lost, before trying to call `sendReport` on the `HIDDevice`.
- Multi device support: the previous implementation was not able to handle multiple devices of the same model as we can't get a unique identifier from a device.
- Previously, successively connecting 2 devices of the same model would break the 1st of the 2 sessions, it's not the case anymore.
- Reconnection logic: it is now more robust.
- Overall I hope that the code is now easier to read and maintain.
Rework `WebUsbHidTransport` internal logic & reconnection logic:
- Stop relying on our own generated `deviceId` for internal mapping of discovered/connected devices, rely on the identity of `HIDDevice` instead:
- we only have a …

♻️ (core) [DSDK-503]: Improve WebHID reconnection logic & internal logic

---

packages/signer/keyring-btc/src/internal/data-store/di/dataStoreModule.test.ts
packages/signer/keyring-btc/src/internal/data-store/di/dataStoreModule.ts
packages/signer/keyring-btc/src/internal/data-store/di/dataStoreTypes.ts
packages/signer/keyring-btc/src/internal/data-store/model/DataStore.test.ts
packages/signer/keyring-btc/src/internal/data-store/model/DataStore.ts
packages/signer/keyring-btc/src/internal/data-store/service/DataStoreService.ts
packages/signer/keyring-btc/src/internal/data-store/service/DefaultDataStoreService.test.ts
packages/signer/keyring-btc/src/internal/data-store/service/DefaultDataStoreService.ts

The idea is to implement a service that will be in charge store data required to respond to Client Commands that are:
* GetPreimage
* GetMerkleLeafIndex
* GetMerkleProof
More informations in the ticket
- **JIRA**: https://ledgerhq.atlassian.net/browse/DSDK-460
Pull Requests must pass the CI and be code reviewed. Set as Draft if the PR is not ready.
- ...
---

:sparkles: (keyring-btc) [DSDK-460]: Implement a data store service

---

.changeset/loud-balloons-poke.md
packages/signer/keyring-eth/package.json
packages/signer/keyring-eth/src/internal/app-binder/task/BuildEIP712ContextTask.test.ts
packages/signer/keyring-eth/src/internal/app-binder/task/BuildEIP712ContextTask.ts
pnpm-lock.yaml

Add support of older ethereum app versions: before 1.11.0, we should use clear signing context V1 for EIP712, instead of V2.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/DSDK-433
- **Feature**:
---

:sparkles: (keyring-eth) [DSDK-433]: Add support for V1 clear signing contexts

---

.github/workflows/update_toolchain.yml

Since the update-toolchain.yml workflow uses a GIHTUB_TOKEN to create the PR, the CI for the PR workflow is not run (security measure to prevent a infinite loops)
Thus I added the test directly in the workflow that does the update, meaning the PR won't have any checks, but the test will be passed before the PR is created, so we can safely merge it. 
However, if we need to rebase the created PR (`chore/update-toolchain`), the CI will trigger as usual so no issues there
- **Feature**:
---

💚 (repo) [NO-ISSUE]: Trigger PR tests after toolchain update

---

.changeset/great-paws-sell.md
packages/signer/context-module/src/typed-data/domain/DefaultTypedDataContextLoader.test.ts
packages/signer/context-module/src/typed-data/domain/DefaultTypedDataContextLoader.ts
packages/signer/keyring-eth/src/internal/app-binder/task/BuildEIP712ContextTask.test.ts
packages/signer/keyring-eth/src/internal/app-binder/task/BuildEIP712ContextTask.ts
packages/signer/keyring-eth/src/internal/app-binder/task/ProvideEIP712ContextTask.test.ts
packages/signer/keyring-eth/src/internal/app-binder/task/ProvideEIP712ContextTask.ts

Currently, when we have an EIP712 filter referencing a token, which is missing from the CAL, the whole message signing fails...
This was fixed in 1.12.0 version of ethereum app, which now supports missing tokens and just display a warning to the user (??? placeholder).
This can be tested with supported messages (such as https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledgerjs/packages/hw-app-eth/tests/fixtures/messages/18-1inch-fusion.json) by modifying token address values to an unknown address.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/DSDK-536
- **Feature**:
---

:sparkles: (keyring-eth) [DSDK-536]: Add support for EIP712 filters with missing token

---

.changeset/ten-carrots-wait.md
packages/signer/keyring-eth/src/internal/app-binder/command/SignTransactionCommand.test.ts
packages/signer/keyring-eth/src/internal/app-binder/command/SignTransactionCommand.ts
packages/signer/keyring-eth/src/internal/app-binder/command/StartTransactionCommand.ts
packages/signer/keyring-eth/src/internal/app-binder/task/SendSignTransactionTask.test.ts
packages/signer/keyring-eth/src/internal/app-binder/task/SendSignTransactionTask.ts

The spec has been updated and there is no need to handle a legacy sign transaction command.
- **Feature**:
---

🔥 (keyring-eth) [NO-ISSUE]: Remove legacy parameter for sign transaction

---

.changeset/twelve-snakes-agree.md
apps/sample/package.json
apps/sample/src/components/AvailableDevices/index.tsx
apps/sample/src/components/Device/index.tsx
apps/sample/src/components/MainView/ConnectDeviceActions.tsx
apps/sample/src/components/MainView/index.tsx
apps/sample/src/components/Sidebar/index.tsx
apps/sample/src/hooks/useAvailableDevices.tsx
apps/sample/src/hooks/useHasChanged.tsx
apps/sample/src/hooks/usePrevious.ts
apps/sample/src/providers/DeviceSdkProvider/index.tsx
apps/sample/src/providers/DeviceSessionsProvider/index.tsx
apps/sample/src/reducers/deviceSessions.ts
apps/sample/src/styles/globalstyles.tsx
packages/core/src/api/DeviceSdk.ts
packages/core/src/api/transport/model/Transport.ts
packages/core/src/internal/discovery/di/discoveryModule.test.ts
packages/core/src/internal/discovery/di/discoveryModule.ts
packages/core/src/internal/discovery/di/discoveryTypes.ts
packages/core/src/internal/discovery/use-case/ListenToKnownDevicesUseCase.test.ts
packages/core/src/internal/discovery/use-case/ListenToKnownDevicesUseCase.ts
packages/core/src/internal/transport/ble/transport/WebBleTransport.ts
packages/core/src/internal/transport/ble/transport/__mocks__/WebBleTransport.ts
packages/core/src/internal/transport/mockserver/MockserverTransport.ts
packages/core/src/internal/transport/usb/transport/WebUsbHidTransport.test.ts
packages/core/src/internal/transport/usb/transport/WebUsbHidTransport.ts
packages/core/src/internal/transport/usb/transport/__mocks__/WebUsbHidTransport.ts
pnpm-lock.yaml

This new feature allows to observe an array of available devices, as `DiscoveredDevice`.
For WebHID, it means that for devices for which the user has already granted an authorization to the app (via `navigator.hid.requestDevice()`), plugging in a device will make it appear in that array, and unplugging it will make it disappear.
In case of reconnection (in an open/close app for instance), internally, the `HIDDevice` will be a different instance, but we keep the same `DeviceId` so that from the app's point of view, we can identify which of the `DiscoveredDevice` already has an ongoing session.
https://github.com/user-attachments/assets/ce5c5598-f2ff-4183-9177-466644ab7cee
- **JIRA or GitHub link**: [[DSDK-504]](https://ledgerhq.atlassian.net/jira/software/c/projects/DSDK/boards/817?assignee …

✨ (core) [DSDK-504]: Listen to known devices (WebHID for now) & display them in sample app

---

.changeset/fast-planes-cover.md
packages/signer/signer-solana/src/internal/app-binder/command/GetAppConfigurationCommand.test.ts
packages/signer/signer-solana/src/internal/app-binder/command/GetAppConfigurationCommand.ts

Added getAppConfigurationCommand
- **JIRA or GitHub link**: [DSDK-552](https://ledgerhq.atlassian.net/browse/DSDK-552)
---
[DSDK-552]: https://ledgerhq.atlassian.net/browse/DSDK-552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

✨ (signer-solana) [DSDK-552]: Added getAppConfigurationCommand

---

.changeset/clever-badgers-pull.md
.changeset/old-impalas-beam.md
apps/sample/package.json
apps/sample/src/app/keyring/solana/page.tsx
apps/sample/src/components/KeyringView/index.tsx
apps/sample/src/components/SignerSolanaView/index.tsx
packages/signer/signer-solana/package.json
packages/signer/signer-solana/src/api/index.ts
packages/signer/signer-solana/src/index.ts
packages/signer/signer-solana/src/internal/DefaultSignerSolana.ts
packages/signer/signer-solana/src/internal/app-binder/SolanaAppBinder.test.ts
packages/signer/signer-solana/src/internal/app-binder/SolanaAppBinder.ts
packages/signer/signer-solana/src/internal/di.ts
packages/signer/signer-solana/src/internal/use-cases/address/GetAddressUseCase.test.ts
packages/signer/signer-solana/src/internal/use-cases/address/GetAddressUseCase.ts
packages/signer/signer-solana/src/internal/use-cases/di/useCasesModule.test.ts
packages/signer/signer-solana/src/internal/use-cases/di/useCasesModule.ts
packages/signer/signer-solana/src/internal/use-cases/di/useCasesTypes.ts
pnpm-lock.yaml

Add `GetAddressUseCase` implementation for the `signer-solana`.
Add signer view in the playground app.
https://github.com/user-attachments/assets/b16b8616-80c7-4a33-8a27-0cb489031504
- **JIRA or GitHub link**: [DSDK-554]
- **Feature**:
---
[DSDK-554]: https://ledgerhq.atlassian.net/browse/DSDK-554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

✨ (signer-solana) [DSDK-554]: Add GetAddressUseCase

---

.changeset/fresh-walls-jam.md
packages/signer/signer-solana/src/internal/app-binder/command/SignOffChainMessageCommand.test.ts
packages/signer/signer-solana/src/internal/app-binder/command/SignOffChainMessageCommand.ts
packages/signer/signer-solana/src/internal/app-binder/device-action/__test-utils__/makeInternalApi.ts
packages/signer/signer-solana/src/internal/app-binder/task/SendCommandInChunksTask.ts
packages/signer/signer-solana/src/internal/app-binder/task/SendSignDataTask.test.ts
packages/signer/signer-solana/src/internal/app-binder/task/SendSignDataTask.ts

Add solana SignDataTask and utils 
- **JIRA or GitHub link**: [DSDK-564](https://ledgerhq.atlassian.net/browse/DSDK-564)
---
[DSDK-564]: https://ledgerhq.atlassian.net/browse/DSDK-564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

✨ (signer-solana) [DSDK-564]: Add solana SignDataTask and utils

---

.changeset/hip-ducks-study.md
packages/signer/context-module/src/typed-data/domain/DefaultTypedDataContextLoader.test.ts
packages/signer/context-module/src/typed-data/domain/DefaultTypedDataContextLoader.ts
packages/signer/signer-eth/src/internal/app-binder/command/SendEIP712FilteringCommand.test.ts
packages/signer/signer-eth/src/internal/app-binder/command/SendEIP712FilteringCommand.ts
packages/signer/signer-eth/src/internal/app-binder/task/ProvideEIP712ContextTask.test.ts
packages/signer/signer-eth/src/internal/app-binder/task/ProvideEIP712ContextTask.ts

Full description available in the Jira ticket.
The goal is to correctly handle clear signing of EIP712 messages when an array is empty.
To do that, we should discard filters of all the fields contained in such arrays.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/DSDK-530
- **Feature**: Fix clear signing of EIP712 messages with an empty array
---

:sparkles: (keyring-eth) [DSDK-530]: Handle empty arrays with filters

---

.changeset/lemon-impalas-flash.md
packages/signer/signer-eth/src/api/SignerEth.ts
packages/signer/signer-eth/src/api/app-binder/SignPersonalMessageDeviceActionTypes.ts
packages/signer/signer-eth/src/internal/DefaultSignerEth.ts
packages/signer/signer-eth/src/internal/app-binder/EthAppBinder.ts
packages/signer/signer-eth/src/internal/app-binder/device-action/SignPersonalMessage/SignPersonalMessageDeviceAction.ts
packages/signer/signer-eth/src/internal/app-binder/task/SendSignPersonalMessageTask.test.ts
packages/signer/signer-eth/src/internal/app-binder/task/SendSignPersonalMessageTask.ts
packages/signer/signer-eth/src/internal/message/use-case/SignMessageUseCase.ts

Allow to give a byte array as personal message to be signed.
It can be useful for some usecases such as signing a hash
- **Feature**:
---

:sparkles: (signer-eth) [NO-ISSUE]: Allow signing a message as a byte array

---

.changeset/pink-hats-battle.md
.changeset/spicy-toes-ring.md
apps/sample/src/components/SignerSolanaView/index.tsx
packages/signer/signer-solana/src/api/app-binder/SignTransactionDeviceActionTypes.ts
packages/signer/signer-solana/src/api/index.ts
packages/signer/signer-solana/src/internal/DefaultSignerSolana.test.ts
packages/signer/signer-solana/src/internal/DefaultSignerSolana.ts
packages/signer/signer-solana/src/internal/app-binder/SolanaAppBinder.test.ts
packages/signer/signer-solana/src/internal/app-binder/SolanaAppBinder.ts
packages/signer/signer-solana/src/internal/app-binder/command/SignTransactionCommand.test.ts
packages/signer/signer-solana/src/internal/app-binder/command/SignTransactionCommand.ts
packages/signer/signer-solana/src/internal/app-binder/device-action/SignTransactionDeviceAction.test.ts
packages/signer/signer-solana/src/internal/app-binder/device-action/SignTransactionDeviceAction.ts
packages/signer/signer-solana/src/internal/app-binder/device-action/__test-utils__/setupOpenAppDAMock.ts
packages/signer/signer-solana/src/internal/app-binder/device-action/__test-utils__/testDeviceActionStates.ts
packages/signer/signer-solana/src/internal/app-binder/task/SendCommandInChunksTask.ts
packages/signer/signer-solana/src/internal/app-binder/task/SendSignDataTask.test.ts
packages/signer/signer-solana/src/internal/app-binder/task/SendSignDataTask.ts
packages/signer/signer-solana/src/internal/use-cases/di/useCasesModule.test.ts
packages/signer/signer-solana/src/internal/use-cases/di/useCasesModule.ts
packages/signer/signer-solana/src/internal/use-cases/di/useCasesTypes.ts
packages/signer/signer-solana/src/internal/use-cases/transaction/SignTransactionUseCase.test.ts
packages/signer/signer-solana/src/internal/use-cases/transaction/SignTransactionUseCase.ts

Add Sign Transaction Use case in sample and Solana signer kit.
https://github.com/user-attachments/assets/c0283f62-b918-43c2-b44f-5349f227ed81
- **Feature**: [DSDK-565]
---
[DSDK-565]: https://ledgerhq.atlassian.net/browse/DSDK-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

✨ (signer-solana) [DSDK-565]: Implement SignTransaction usecase

---

.changeset/tender-starfishes-cover.md
apps/sample/src/components/SignerSolanaView/index.tsx
packages/signer/signer-eth/src/internal/message/use-case/SignMessageUseCase.ts
packages/signer/signer-solana/src/api/index.ts
packages/signer/signer-solana/src/internal/DefaultSignerSolana.test.ts
packages/signer/signer-solana/src/internal/DefaultSignerSolana.ts
packages/signer/signer-solana/src/internal/app-binder/SolanaAppBinder.test.ts
packages/signer/signer-solana/src/internal/app-binder/SolanaAppBinder.ts
packages/signer/signer-solana/src/internal/app-binder/command/SignOffChainMessageCommand.test.ts
packages/signer/signer-solana/src/internal/app-binder/command/SignOffChainMessageCommand.ts
packages/signer/signer-solana/src/internal/app-binder/command/SignTransactionCommand.test.ts
packages/signer/signer-solana/src/internal/app-binder/device-action/SignMessage/SignMessageDeviceAction.test.ts
packages/signer/signer-solana/src/internal/app-binder/device-action/SignMessage/SignMessageDeviceAction.ts
packages/signer/signer-solana/src/internal/app-binder/task/SendSignMessageTask.test.ts
packages/signer/signer-solana/src/internal/app-binder/task/SendSignMessageTask.ts
packages/signer/signer-solana/src/internal/use-cases/di/useCasesModule.test.ts
packages/signer/signer-solana/src/internal/use-cases/di/useCasesModule.ts
packages/signer/signer-solana/src/internal/use-cases/di/useCasesTypes.ts
packages/signer/signer-solana/src/internal/use-cases/message/SignMessageUseCase.test.ts
packages/signer/signer-solana/src/internal/use-cases/message/SignMessageUseCase.ts

Added Solana SignMessageUseCase
- **JIRA or GitHub link**: [DSDK-566](https://ledgerhq.atlassian.net/browse/DSDK-566)
---
[DSDK-566]: https://ledgerhq.atlassian.net/browse/DSDK-566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

✨ (signer-solana) [DSDK-566]: Add solana SignMessageUseCase

---

.changeset/clean-zoos-battle.md
packages/device-management-kit/CHANGELOG.md
packages/device-management-kit/package.json
packages/flipper-plugin-client/CHANGELOG.md
packages/flipper-plugin-client/package.json
packages/signer/signer-solana/CHANGELOG.md
packages/signer/signer-solana/package.json
packages/signer/signer-utils/CHANGELOG.md
packages/signer/signer-utils/package.json
packages/transport-mock/CHANGELOG.md
packages/transport-mock/package.json

Hotfix for DMK 0.5.0 which requires `@ledgerhq/device-transport-kit-mock-client` in its dependencies but was private.
Updatng `@ledgerhq/device-transport-kit-mock-client` to public and publishing a new version of DMK (0.5.1)
- **Feature**:
---

🔖 (hotfix) [NO-ISSUE]: DMK v0.5.1 + Transport Mock Client v1.1.0

---

.changeset/metal-tables-move.md
packages/device-management-kit/src/api/DeviceManagementKit.test.ts
packages/device-management-kit/src/api/DeviceManagementKit.ts
packages/device-management-kit/src/api/device-session/use-case/ToggleDeviceSessionRefresher.test.ts
packages/device-management-kit/src/api/device-session/use-case/ToggleDeviceSessionRefresher.ts
packages/device-management-kit/src/internal/device-session/di/deviceSessionModule.ts
packages/device-management-kit/src/internal/device-session/di/deviceSessionTypes.ts
packages/device-management-kit/src/internal/device-session/model/DeviceSession.ts
packages/device-management-kit/src/internal/device-session/model/DeviceSessionRefresher.test.ts
packages/device-management-kit/src/internal/device-session/model/DeviceSessionRefresher.ts
packages/device-management-kit/src/internal/device-session/model/Errors.ts

Add new method to toggle on or off the device session refresher (LLD integration requirement)
- **Feature**:
- devicesession and refresher
- new usecase
---

✨ (dmk) [NO-ISSUE]: Add new ToggleDeviceSessionRefresher method

---

.changeset/clean-bobcats-greet.md
packages/signer/context-module/src/transaction/data/HttpTransactionDataSource.test.ts
packages/signer/context-module/src/transaction/data/HttpTransactionDataSource.ts

Iterate on transaction calldata descriptors to avoid empty objects.
- **JIRA or GitHub link**: [DSDK-615]
- **Feature**:
---
[DSDK-615]: https://ledgerhq.atlassian.net/browse/DSDK-615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

🐛 (context-module) [DSDK-615]: Iterate on transaction calldata

---

apps/sample/package.json

Package json conflict resolution
- **Feature**:
---

:lipstick: (smpl) [NO-ISSUE]: Fix package json conflict

---

.changeset/green-jobs-pay.md
packages/device-management-kit/src/api/device-action/DeviceAction.ts
packages/device-management-kit/src/api/device-action/__test-utils__/makeInternalApi.ts
packages/device-management-kit/src/api/device-action/os/ListAppsWithMetadata/ListAppsWithMetadataDeviceAction.test.ts
packages/device-management-kit/src/api/device-action/os/ListAppsWithMetadata/ListAppsWithMetadataDeviceAction.ts
packages/device-management-kit/src/internal/device-session/model/DeviceSession.ts
packages/signer/signer-btc/src/internal/app-binder/device-action/__test-utils__/makeInternalApi.ts
packages/signer/signer-eth/src/internal/app-binder/device-action/__test-utils__/makeInternalApi.ts
packages/signer/signer-solana/src/internal/app-binder/device-action/__test-utils__/makeInternalApi.ts

Get Manager API service from `InternalApi` interface in order to get each necessary service from it.
- **Feature**:
---

✨ (dmk) [NO-ISSUE]: Get manager API service from internal API

---

packages/transport/web-ble/src/api/transport/BleDeviceConnection.ts

This fix aims to resolve the issue in this [dependabot PR](https://github.com/LedgerHQ/device-sdk-ts/pull/579) by adding a type check of `buffer` variable to ensure it's an `ArrayBuffer`.
- **Feature**:
---

♻️ (dmk) [NO-ISSUE]: Add type check

---

.changeset/chilly-carpets-press-2.md
.changeset/chilly-carpets-press.md
.changeset/grumpy-tables-taste.md
.changeset/ten-lions-report.md
packages/device-management-kit/package.json
packages/device-management-kit/src/api/Error.ts
packages/device-management-kit/src/api/index.ts
packages/device-management-kit/src/internal/device-session/model/DeviceSession.ts
packages/device-management-kit/src/internal/device-session/model/Errors.ts
packages/transport/web-ble/package.json
packages/transport/web-hid/package.json
packages/transport/web-hid/src/api/transport/WebHidDeviceConnection.test.ts
packages/transport/web-hid/src/api/transport/WebHidDeviceConnection.ts

This PR updates the DMK to better handle the LLD integration.
**DMK**
Updates the DeviceSession to handle resetting the device status when an error happens
**WebHidTransport**
Update the WebHidDeviceConnection for reconnection issues
- **JIRA or GitHub link**: [NO-ISSUE] LLD integration
- **Feature**:
---

👔 (dmk) [NO-ISSUE]: Update DeviceSession + WebHidTransport reconnection update

---

.changeset/six-buses-pump.md
packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.test.ts
packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.ts
packages/signer/signer-eth/src/internal/app-binder/device-action/SignTypedData/SignTypedDataDeviceAction.test.ts
packages/signer/signer-eth/src/internal/app-binder/device-action/SignTypedData/SignTypedDataDeviceAction.ts
packages/signer/signer-eth/src/internal/app-binder/task/BuildEIP712ContextTask.test.ts
packages/signer/signer-eth/src/internal/app-binder/task/BuildEIP712ContextTask.ts
packages/signer/signer-eth/src/internal/app-binder/task/BuildTransactionContextTask.test.ts
packages/signer/signer-eth/src/internal/app-binder/task/BuildTransactionContextTask.ts
packages/signer/signer-eth/src/internal/app-binder/task/ProvideEIP712ContextTask.test.ts
packages/signer/signer-eth/src/internal/app-binder/task/ProvideEIP712ContextTask.ts

Update the signer ethereum device action to fallback on blind signing when some commands are not supported.
- `SignTransaction`: Fallback to blind sign transaction if getChallenge does not work
- `SignTypedObject`: Fallback to legacy signing if provide does not work.
- **JIRA or GitHub link**: [DSDK-633]
- **Feature**:
---
[DSDK-633]: https://ledgerhq.atlassian.net/browse/DSDK-633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

🐛 (signer-eth) [DSDK-633]: Fallback on legacy signing

---

.changeset/fuzzy-dryers-speak.md
apps/sample/src/components/DeviceActionsView/DeviceActionResponse.tsx

In the sample app, device actions results are currently logged through a simple `JSON.stringify`.
That's not readable for `Uint8Array` buffers such as signatures, or public keys.
It's especially visible when signing a bitcoin PSBT.
With that PR, the result is shown as
{
"status": "completed",
"output": [
{
"inputIndex": 0,
"signature": "0x3044022077ad57e037df32da3ef3e95279ae5d2a5f0b2d5cf18e4623e66f0172458546e802207bbe945fd1b0e42279752449295a8a042a8ba8c409ef10ea146fd8112e511b1a01",
"pubkey": "0x028220639970ba251fdea46ad8ce0017df7e53f2cc065e41d55d5111110685a628"
},
{
"inputIndex": 1,
"signature": "0x3045022100ef37773e74c769c9246d10e23c991a14d864661e496b1b128a85af285c64d14102201e6b24b6ee89838ebe83ddc52fa5e530f86dacfd8d5ce7a3290212fa10b80ecb01",
"pubkey": …

:lipstick: (smpl) [NO-ISSUE]: Pretty print buffers in device actions logs

---

.changeset/funny-rockets-glow.md
packages/signer/signer-eth/src/internal/app-binder/device-action/SignTypedData/SignTypedDataDeviceAction.test.ts
packages/signer/signer-eth/src/internal/app-binder/device-action/SignTypedData/SignTypedDataDeviceAction.ts

Restore the user interaction during the provide `SignTypedObjectDA` that was removed. 
- **Feature**:
---

🩹 (signer-eth) [NO-ISSUE]: Add review user interraction for sign typed obj

---

.changeset/selfish-maps-rhyme.md
apps/sample/src/components/SignerBtcView/SignPsbtDAInputValusForm.tsx
apps/sample/src/components/SignerBtcView/index.tsx
packages/signer/signer-btc/package.json
packages/signer/signer-btc/src/api/SignerBtc.ts
packages/signer/signer-btc/src/api/app-binder/SignPsbtDeviceActionTypes.ts
packages/signer/signer-btc/src/api/app-binder/SignTransactionDeviceActionTypes.ts
packages/signer/signer-btc/src/api/index.ts
packages/signer/signer-btc/src/internal/DefaultSignerBtc.test.ts
packages/signer/signer-btc/src/internal/DefaultSignerBtc.ts
packages/signer/signer-btc/src/internal/app-binder/BtcAppBinder.ts
packages/signer/signer-btc/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.test.ts
packages/signer/signer-btc/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.ts
packages/signer/signer-btc/src/internal/app-binder/device-action/__test-utils__/setupSignPsbtDAMock.ts
packages/signer/signer-btc/src/internal/app-binder/task/ExtractTransactionTask.test.ts
packages/signer/signer-btc/src/internal/app-binder/task/ExtractTransactionTask.ts
packages/signer/signer-btc/src/internal/app-binder/task/UpdatePsbtTask.test.ts
packages/signer/signer-btc/src/internal/app-binder/task/UpdatePsbtTask.ts
packages/signer/signer-btc/src/internal/psbt/model/Psbt.test.ts
packages/signer/signer-btc/src/internal/psbt/model/Psbt.ts
packages/signer/signer-btc/src/internal/psbt/service/value/DefaultValueFactory.ts
packages/signer/signer-btc/src/internal/psbt/service/value/DefaultValueParser.test.ts
packages/signer/signer-btc/src/internal/psbt/service/value/DefaultValueParser.ts
packages/signer/signer-btc/src/internal/psbt/service/value/ValueParser.ts
packages/signer/signer-btc/src/internal/use-cases/di/useCasesModule.ts
packages/signer/signer-btc/src/internal/use-cases/di/useCasesTypes.ts
packages/signer/signer-btc/src/internal/use-cases/sign-transaction/SignTransactionUseCase.test.ts
packages/signer/signer-btc/src/internal/use-cases/sign-transaction/SignTransactionUseCase.ts
packages/signer/signer-btc/src/internal/utils/ScriptOperation.test.ts
packages/signer/signer-btc/src/internal/utils/ScriptOperation.ts

- Update PSBT task
- Extract transaction task
- Sign transaction DA
https://github.com/user-attachments/assets/68c6e9b1-e76b-4302-89c5-b84f8d3e6c83
- **JIRA or GitHub link**: [DSDK-472] [DSDK-473] [DSDK-479] [DSDK-484]
- **Feature**:
---
[DSDK-472]: https://ledgerhq.atlassian.net/browse/DSDK-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DSDK-473]: https://ledgerhq.atlassian.net/browse/DSDK-473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DSDK-479]: https://ledgerhq.atlassian.net/browse/DSDK-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …

:sparkles: (signer-btc) [DSDK-472]: Implement update PSBT and extract transaction

---

.changeset/chatty-rings-collect.md
packages/signer/signer-btc/README.md
packages/signer/signer-eth/README.md
packages/signer/signer-solana/README.md

Polished signers readme and added BTC readme
---

📝 (signers) [NO-ISSUE]: Polish signer's readme

---

.changeset/popular-waves-exist.md
packages/signer/signer-eth/src/internal/transaction/service/parser/TransactionParserService.test.ts
packages/signer/signer-eth/src/internal/transaction/service/parser/TransactionParserService.ts

Generic parser allow a slice of static leafs on device side, and the CAL descriptors will also soon allow it:
https://github.com/LedgerHQ/clear-signing-erc7730-registry/pull/102
Therefore the SignerEth transaction parser should also be able to slice static leafs and read data such as addresses in bigger chunks
- **Feature**:
---

:sparkles: (signer-eth) [NO-ISSUE]: Allow to slice static leafs

---

.changeset/chilly-dancers-yell.md
apps/sample/src/components/SignerBtcView/SignPsbtDAInputValusForm.tsx
apps/sample/src/components/SignerBtcView/index.tsx

Fix of small issues in the BTC device action UI
- Allow to select a descriptor template
- Automatically update default derivation path depending on template
- Add title before addressIndex input
- Improve addressIndex input behaviour using validateValues
- **Feature**:
---

:lipstick: (smpl) [NO-ISSUE]: SignerBtcView various improvements

---

.github/workflows/sync_doc.yml

Adds a new workflow to sync our documentation to the developer-portal when merging to `main`
- **Feature**:
---

👷 (doc) [NO-ISSUE]: Sync doc with ledgerhq/developer-portal

---

README.md
danger/helpers.ts
packages/device-management-kit/README.md
packages/transport/web-ble/README.md
packages/transport/web-hid/README.md

Add missing README.md to transport packages and update DMK README.md
- **Feature**:
---

📝 (transports) [NO-ISSUE]: Add missing readme.md to transport packages

---

.changeset/fuzzy-spies-divide.md
packages/transport/web-hid/src/api/transport/WebHidDeviceConnection.test.ts
packages/transport/web-hid/src/api/transport/WebHidDeviceConnection.ts

Check for the timing between reconnection before sending an error everytime.
- **Feature**:
---

👔 (webhid) [NO-ISSUE]: Update reconnection error sending

---

.changeset/gorgeous-readers-eat.md
packages/device-management-kit/package.json
packages/signer/signer-btc/package.json
packages/signer/signer-solana/package.json
packages/signer/signer-utils/package.json
packages/transport/web-ble/package.json
packages/transport/web-hid/package.json
packages/transport/web-hid/src/api/transport/WebHidDeviceConnection.test.ts
packages/transport/web-hid/src/api/transport/WebHidDeviceConnection.ts

Make sure to cancel the previous apdusubject in case of full disconnection / reconnection
- **Feature**:
---

🐛 (webhid) [NO-ISSUE]: Reconnection fixes

---

.changeset/funny-ads-destroy.md
.changeset/gold-needles-sell.md
.changeset/grumpy-olives-shave.md
.changeset/smooth-fireants-sip.md
packages/device-management-kit/package.json
packages/device-management-kit/src/api/device-action/DeviceAction.ts
packages/device-management-kit/src/api/device-action/__test-utils__/makeInternalApi.ts
packages/device-management-kit/src/internal/device-session/model/DeviceSession.ts
packages/signer/signer-btc/package.json
packages/signer/signer-btc/src/internal/app-binder/device-action/__test-utils__/makeInternalApi.ts
packages/signer/signer-eth/package.json
packages/signer/signer-eth/src/internal/app-binder/device-action/__test-utils__/makeInternalApi.ts
packages/signer/signer-solana/package.json
packages/signer/signer-solana/src/internal/app-binder/device-action/__test-utils__/makeInternalApi.ts

Add `sendApdu` method in `InternalApi` interface and adapt unit tests in other packages.
- **Feature**:
- Now `InternalApi` has `sendApdu` method that allows to send a pure APDU of type `Uint8Array`.
---

✨ (dmk) [NO-ISSUE]: Add sendApdu in internal API interface

---

.changeset/healthy-donuts-divide.md
packages/device-management-kit/package.json
packages/device-management-kit/src/api/device-action/xstate-utils/XStateDeviceAction.ts
pnpm-lock.yaml

Move statelyai/inspect to devDependencies
- **Feature**:
---

➖ (dmk) [NO-ISSUE]: Remove statelyai/inspect from dependencies

---

.changeset/real-sheep-join.md
apps/sample/src/hooks/useAvailableDevices.tsx
packages/device-management-kit/src/api/DeviceManagementKit.ts
packages/device-management-kit/src/api/transport/model/Errors.ts
packages/device-management-kit/src/internal/discovery/use-case/ListenToAvailableDevicesUseCase.test.ts
packages/device-management-kit/src/internal/discovery/use-case/ListenToAvailableDevicesUseCase.ts

Allow to filter by specific transports
Allows listenToAvailableDevices to check only for a given transport
- **Feature**:
---

👔 (dmk) [NO-ISSUE]: Update listenToAvailableDevices

---

.github/workflows/update_toolchain.yml

Create upstream branch before using github api to create commit
- **Feature**:
---

💚 (commits) [NO-ISSUE]: Fix creation of branch before using gh api

---

.changeset/pink-doors-joke.md
packages/device-management-kit/package.json
packages/device-management-kit/src/internal/device-session/model/DeviceSession.ts
packages/transport/web-ble/package.json
packages/transport/web-hid/package.json

Hotfix release
- Fixes an issue in the DeviceSession where in case the refresher is disabled, we would be in limbo if we send an apdu to a locked device
- **Feature**:
---

🚑️ (hotfix) [NO-ISSUE]: Release device-management-kit 0.6.3

---

.changeset/little-icons-complain.md
packages/device-management-kit/src/api/device-action/model/UserInteractionRequired.ts
packages/signer/signer-eth/src/api/app-binder/SignTransactionDeviceActionTypes.ts
packages/signer/signer-eth/src/api/app-binder/SignTypedDataDeviceActionTypes.ts
packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.test.ts
packages/signer/signer-eth/src/internal/app-binder/device-action/SignTransaction/SignTransactionDeviceAction.ts
packages/signer/signer-eth/src/internal/app-binder/device-action/SignTypedData/SignTypedDataDeviceAction.test.ts
packages/signer/signer-eth/src/internal/app-binder/device-action/SignTypedData/SignTypedDataDeviceAction.ts
packages/signer/signer-eth/src/internal/app-binder/task/BuildEIP712ContextTask.test.ts
packages/signer/signer-eth/src/internal/app-binder/task/BuildEIP712ContextTask.ts
packages/signer/signer-eth/src/internal/app-binder/task/BuildTransactionContextTask.test.ts
packages/signer/signer-eth/src/internal/app-binder/task/BuildTransactionContextTask.ts
packages/signer/signer-eth/src/internal/app-binder/task/GetWeb3CheckTask.test.ts
packages/signer/signer-eth/src/internal/app-binder/task/GetWeb3CheckTask.ts
packages/signer/signer-eth/src/internal/shared/utils/ApplicationChecker.test.ts
packages/signer/signer-eth/src/internal/shared/utils/ApplicationChecker.ts

When web3check opt-in is triggered, the is a need for user interaction on device.
Therefore we need a specific state in device actions to make that user interaction visible on the UI.
Impacted device actions:
* SignTransaction
* SignTypedData
Since SignTransaction was needlessly complex, I took the chance to simplify it before adding the new state.
The review can be done separately on the too commits
- **Feature**:
---

:sparkles: (signer-eth) [NO-ISSUE]: Add a user interaction for web3checks opt-in in device actions

---

.changeset/strange-rules-hang.md
packages/signer/signer-eth/src/internal/app-binder/constant/plugins.ts
packages/signer/signer-eth/src/internal/shared/utils/ApplicationChecker.test.ts
packages/signer/signer-eth/src/internal/shared/utils/ApplicationChecker.ts

Bug reproduced when doing swaps with a centralized exchange in Ledger Live, from Eth to another chain.
The flow should be done in Exchange App, but the SignerEth tries to open Ethereum app at the end of the flow to sign the TX, which break the flow.
https://ledgerhq.atlassian.net/browse/DSDK-723
- **Feature**:
---

:bug: (signer-eth) [DSDK-723]: SignerEth should be compatible with Exchange app flows

---

.changeset/fast-bags-roll.md
packages/device-management-kit/src/api/device-action/os/GetDeviceStatus/GetDeviceStatusDeviceAction.test.ts
packages/device-management-kit/src/api/device-action/os/GetDeviceStatus/GetDeviceStatusDeviceAction.ts

The GetDeviceStatus device action currently rely on the device session to know if a device is locked or not.
It means that when the refresher is disabled, a locked device will stay locked forever in the DMK session, even if the user unlocked it.
The solution is to synchronously get the lock status in GetDeviceStatus instead of reading the session state
https://ledgerhq.atlassian.net/browse/DSDK-749
- **Feature**:
---

:bug: (dmk) [DSDK-749]: Don't rely on refresher in GetDeviceStatus device action

---

.changeset/unlucky-fans-tell.md
packages/device-management-kit/src/api/device-action/os/GetDeviceStatus/GetDeviceStatusDeviceAction.test.ts
packages/device-management-kit/src/api/device-action/os/GetDeviceStatus/GetDeviceStatusDeviceAction.ts

Bug noticed during Ledger Live integration because of the disabled refresher.
Described here: https://ledgerhq.atlassian.net/browse/DSDK-753
- **Feature**:
---

:bug: (dmk) [DSDK-753]: Update the device session state when refresher is disabled

---

.changeset/tame-yaks-care.md
apps/sample/src/components/DeviceActionsView/AllDeviceActions.tsx
packages/device-management-kit/src/api/device-action/__test-utils__/setupTestMachine.ts
packages/device-management-kit/src/api/device-action/os/Errors.ts
packages/device-management-kit/src/api/device-action/os/GetDeviceMetadata/types.ts
packages/device-management-kit/src/api/device-action/os/GoToDashboard/types.ts
packages/device-management-kit/src/api/device-action/os/InstallOrUpdateApps/types.ts
packages/device-management-kit/src/api/device-action/os/OpenAppWithDependencies/OpenAppWithDependenciesDeviceAction.test.ts
packages/device-management-kit/src/api/device-action/os/OpenAppWithDependencies/OpenAppWithDependenciesDeviceAction.ts
packages/device-management-kit/src/api/device-action/os/OpenAppWithDependencies/types.ts
packages/device-management-kit/src/api/index.ts
packages/device-management-kit/src/api/types.ts

Part of connectApp state machines for Ledger Live migration
Ticket: https://ledgerhq.atlassian.net/browse/DSDK-704
Documentation: https://ledgerhq.atlassian.net/wiki/spaces/WXP/pages/5675549070/OS+Open+application+with+dependencies
- **Feature**:
---

:sparkles: (dmk) [DSDK-704]: Implement OpenAppWithDependencies device action

---

.changeset/warm-radios-tie.md
packages/signer/signer-eth/src/internal/app-binder/task/BuildTransactionContextTask.test.ts
packages/signer/signer-eth/src/internal/app-binder/task/BuildTransactionContextTask.ts

Send USDT fails on LNS, because USDT has an ERC7730 descriptor, but nano S has no certificate (no PKI support).
If device don't support the generic parser, don't verify the certificate
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-18782
- **Feature**:
---

:bug: (signer-eth) [NO-ISSUE]: Don't verify certificate if generic parser is not supported

---

apps/docs/pages/docs/integration/how_to/transports.mdx
apps/sample/package.json
apps/sample/src/components/Header/index.tsx
apps/sample/src/components/MainView/ConnectDeviceActions.tsx
apps/sample/src/providers/DeviceManagementKitProvider/index.tsx
apps/sample/src/reducers/dmkConfig.ts
apps/sample/src/utils/const.ts
package.json
packages/transport/rn-ble/README.md
packages/transport/speculos/.prettierignore
packages/transport/speculos/.prettierrc.js
packages/transport/speculos/README.md
packages/transport/speculos/eslint.config.mjs
packages/transport/speculos/index.ts
packages/transport/speculos/package.json
packages/transport/speculos/src/api/SpeculosTransport.ts
packages/transport/speculos/src/index.ts
packages/transport/speculos/src/internal/datasource/HttpSpeculosDatasource.ts
packages/transport/speculos/src/internal/datasource/SpeculosDatasource.ts
packages/transport/speculos/tsconfig.json
packages/transport/speculos/tsconfig.prod.json
packages/transport/speculos/vitest.config.mjs
pnpm-lock.yaml

Setup Speculos transport
- **Feature**:
---

✨ (transport) [NO-ISSUE]: Create new speculos transport

---

.changeset/weak-walls-joke.md
packages/device-management-kit/src/api/device-action/os/OpenAppDeviceAction/OpenAppDeviceAction.test.ts
packages/device-management-kit/src/api/device-action/os/OpenAppDeviceAction/OpenAppDeviceAction.ts

With BLE transport, we don't always receive the response from OpenApp APDU even if successfully executed.
This is a side effect of known firmware bug, because the device don't properly close BLE transport when an app is opened.
Therefore we should get the device status when that happens, to verify if the app was successfully opened.
This is a fix for https://ledgerhq.atlassian.net/browse/LIVE-19429
Note that this error was handled in legacy connectApp in Ledger Live.
- **Feature**:
---

:bug: (dmk) [NO-ISSUE]: Handle transport disconnection during successful OpenApp

---

.changeset/lucky-numbers-kick.md
packages/device-management-kit/src/api/command/utils/CommandUtils.test.ts
packages/device-management-kit/src/api/command/utils/CommandUtils.ts
packages/device-management-kit/src/api/device-action/os/Errors.ts
packages/device-management-kit/src/api/device-action/os/GetDeviceMetadata/GetDeviceMetadataDeviceAction.ts
packages/device-management-kit/src/api/device-action/os/GetDeviceMetadata/types.ts
packages/device-management-kit/src/api/device-action/os/InstallOrUpdateApps/InstallOrUpdateAppsDeviceAction.ts
packages/device-management-kit/src/api/device-action/os/InstallOrUpdateApps/types.ts
packages/device-management-kit/src/api/index.ts
packages/device-management-kit/src/api/secure-channel/device-action/GenuineCheck/GenuineCheckDeviceAction.ts
packages/device-management-kit/src/api/secure-channel/device-action/GenuineCheck/types.ts
packages/device-management-kit/src/api/secure-channel/device-action/InstallApp/InstallAppDeviceAction.ts
packages/device-management-kit/src/api/secure-channel/device-action/InstallApp/types.ts
packages/device-management-kit/src/api/secure-channel/device-action/ListInstalledApps/ListInstalledAppsDeviceAction.ts
packages/device-management-kit/src/api/secure-channel/device-action/ListInstalledApps/types.ts
packages/device-management-kit/src/api/secure-channel/device-action/UninstallApp/UninstallAppDeviceAction.ts
packages/device-management-kit/src/api/secure-channel/device-action/UninstallApp/types.ts
packages/device-management-kit/src/api/secure-channel/task/ConnectToSecureChannelTask.test.ts
packages/device-management-kit/src/api/secure-channel/task/ConnectToSecureChannelTask.ts
packages/device-management-kit/src/api/secure-channel/task/types.ts
packages/device-management-kit/src/api/secure-channel/utils.test.ts
packages/device-management-kit/src/api/secure-channel/utils.ts
packages/device-management-kit/src/internal/secure-channel/model/Errors.ts

Bug https://ledgerhq.atlassian.net/browse/LIVE-19430
The main issue is that device response status was not verified at all in bulk APDUs sent through secure channels.
It means some errors such as OutOfMemory are not returned properly.
A small refactor is needed to add some typing to secure channel returned errors, and expose it in device actions.
* Error are now properly typed
* Bulk APDUs device status is now verified
* Device actions now expose SecureChannel device errors types
- **Feature**:
---

:bug: (dmk) [NO-ISSUE]: Improve SecureChannel errors management and typing

---

packages/trusted-apps/ledger-keyring-protocol/src/api/app-binder/SignBlockHeaderCommandTypes.ts
packages/trusted-apps/ledger-keyring-protocol/src/api/app-binder/SignBlockSignatureCommandTypes.ts
packages/trusted-apps/ledger-keyring-protocol/src/api/app-binder/SignBlockSingleCommandTypes.ts
packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/command/SignBlockHeader.test.ts
packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/command/SignBlockHeader.ts
packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/command/SignBlockSignatureCommand.test.ts
packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/command/SignBlockSignatureCommand.ts
packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/command/SignBlockSingleCommand.test.ts
packages/trusted-apps/ledger-keyring-protocol/src/internal/app-binder/command/SignBlockSingleCommand.ts

added signBlock commands
- **JIRA or GitHub link**:[DSDK-815](https://ledgerhq.atlassian.net/browse/DSDK-815)
- **Feature**:
---
[DSDK-815]: https://ledgerhq.atlassian.net/browse/DSDK-815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

✨ (keyring) [DSDK-815]: Add signBlock commands
